// packages/frontend/src/app/layout.tsx
// ============================================================================
// 🩹 SURGICAL FIX: Complete Root Layout with correct imports
// ============================================================================
// ✅ FIXED: Correct import path for ClientProviders
// ✅ FIXED: Named import instead of default import
// ✅ FIXED: Next.js 15 metadata and viewport structure
// ============================================================================

import type { Metadata, Viewport } from 'next'
// ✅ SURGICAL FIX: Default import from ./client-providers
import ClientProviders from './client-providers'
import './globals.css'

// ============================================================================
// METADATA CONFIGURATION
// ============================================================================
export const metadata: Metadata = {
  title: 'PSAK 413 Banking Platform',
  description: 'Multi-Tenant Banking PSAK 413 Compliance Platform',
  keywords: [
    'PSAK 413',
    'Banking Platform',
    'Platform Admin',
    'Consultant',
    'Regulator',
    'Financial Compliance',
    'ECL Calculation'
  ],
  authors: [{ name: 'PSAK 413 Platform Team' }],
  creator: 'PSAK 413 Platform Team',
  publisher: 'PSAK 413 Platform',
  robots: process.env.NODE_ENV === 'production' ? 'index, follow' : 'noindex, nofollow',
  manifest: '/manifest.json',
  
  // Open Graph
  openGraph: {
    title: 'PSAK 413 Pro Platform',
    description: 'Multi-Tenant Islamic Banking PSAK 413 Compliance Platform',
    type: 'website',
    locale: 'en_US',
    siteName: 'PSAK 413 Platform',
  },
  
  // Twitter Card
  twitter: {
    card: 'summary_large_image',
    title: 'PSAK 413 Pro Platform',
    description: 'Multi-Tenant Islamic Banking PSAK 413 Compliance Platform',
  },
  
  // Icons
  icons: {
    icon: "/images/logo-ristix.png",
    apple: "/images/logo-ristix.png",
  },
  
  // Format detection
  formatDetection: {
    telephone: false,
    address: false,
    email: false,
  },

  // Additional metadata
  category: 'business',
  classification: 'Banking Software',
  generator: 'Next.js 16',
}

// ============================================================================
// VIEWPORT CONFIGURATION
// ============================================================================
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 5,
  userScalable: true,
  viewportFit: 'cover',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#1976D2' },
    { media: '(prefers-color-scheme: dark)', color: '#1976D2' }
  ],
}

// ============================================================================
// ROOT LAYOUT PROPS INTERFACE
// ============================================================================
interface RootLayoutProps {
  children: React.ReactNode;
}

// ============================================================================
// ROOT LAYOUT COMPONENT
// ============================================================================
export const dynamic = 'force-dynamic';

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html 
      lang="en" 
      suppressHydrationWarning 
      className="h-full"
    >
      <head>
        {/* Additional meta tags */}
        <meta name="application-name" content="IFRS9 Platform" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="IFRS9 Platform" />
        
        {/* Performance optimizations */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="//fonts.googleapis.com" />
        
        {/* Security headers - X-Frame-Options is set via HTTP headers in next.config.mjs */}
        <meta httpEquiv="X-Content-Type-Options" content="nosniff" />
        <meta httpEquiv="X-XSS-Protection" content="1; mode=block" />
        
        {/* Favicon will be auto-generated by Next.js using src/app/icon.png */}
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body 
        className="h-full antialiased"
        style={{ 
          margin: 0,
          fontFamily: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
          backgroundColor: '#fafafa',
          minHeight: '100vh',
          WebkitFontSmoothing: 'antialiased',
          MozOsxFontSmoothing: 'grayscale',
        }}
        suppressHydrationWarning
      >
        {/* ✅ SURGICAL FIX: Use ClientProviders with correct import */}
        <ClientProviders>
          {/* Skip to content link for keyboard/screen reader users */}
          <a
            href="#main-content"
            className="skip-to-content"
            style={{
              position: 'absolute',
              left: -9999,
              top: 'auto',
              width: 1,
              height: 1,
              overflow: 'hidden',
              zIndex: 9999,
              padding: '8px 16px',
              background: '#1976D2',
              color: '#fff',
              textDecoration: 'none',
              fontSize: 14,
            }}
          >
            Skip to main content
          </a>
          <div id="__next" className="h-full">
            {children as any}
          </div>
        </ClientProviders>
      </body>
    </html>
  )
}