// ============================================================================
// PSDD ARTIFACT DOCUMENTATION
// ============================================================================
// File Path: packages/frontend/src/admin/components/common/AdminDashboard.tsx
// Generated: Generated by D2H5 - React Admin Foundation
// Phase: D2H5 - React Admin Foundation
// Methodology: Phased Shell-Driven Development (PSDD)
// Dependencies: React Admin Dashboard, Material-UI
// Purpose: Banking admin dashboard
// ============================================================================

import React from "react";
import { Card, CardContent, Typography, Grid, Box } from "@mui/material";
import { AccountBalance, TrendingUp, People } from "@mui/icons-material";
import { Title } from "react-admin";

export const AdminDashboard: React.FC = () => {
  return (
    <Box p={3}>
      <Title title="IFRS9 | I9 Model" />
      <Typography variant="h4" gutterBottom>
        IFRS9 | ADMIN DASHBOARD
      </Typography>
      
      <Grid container spacing={3}>
        <Grid item xs={12} sm={6} md={4}>
          <Card>
            <CardContent>
              <Box display="flex" alignItems="center" mb={2}>
                <AccountBalance color="primary" sx={{ mr: 2 }} />
                <Typography variant="h6">Total Portfolios</Typography>
              </Box>
              <Typography variant="h4" color="primary">
                12,458
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Active banking portfolios
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        
        <Grid item xs={12} sm={6} md={4}>
          <Card>
            <CardContent>
              <Box display="flex" alignItems="center" mb={2}>
                <TrendingUp color="success" sx={{ mr: 2 }} />
                <Typography variant="h6">ECL Amount</Typography>
              </Box>
              <Typography variant="h4" color="success.main">
                IDR 125.8M
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Current provision level
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        
        <Grid item xs={12} sm={6} md={4}>
          <Card>
            <CardContent>
              <Box display="flex" alignItems="center" mb={2}>
                <People color="secondary" sx={{ mr: 2 }} />
                <Typography variant="h6">Active Users</Typography>
              </Box>
              <Typography variant="h4" color="secondary.main">
                89
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Online banking users
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};
