-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "FRS9_IMP_CA_PD_ENR" (
	"PRC_DATE" date,
	"BUCKET_FROM" varchar(50),
	"CALC_AMOUNT" numeric(20, 2)
);
--> statement-breakpoint
CREATE TABLE "FRS9_IMP_CA_PD_MMULT" (
	"PD_CONFIG_ID" integer,
	"MATRIX_TYPE" varchar(50),
	"MATRIX_VALUE" numeric(10, 4)
);
--> statement-breakpoint
CREATE TABLE "frs9_account_id" (
	"account_id" bigserial NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"facility_number" varchar(50),
	"cif_number" varchar(50),
	"cif_name" varchar(150),
	"createdby" varchar(36) DEFAULT 'SYSTEM',
	"createddate" timestamp DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "FRS9_IMP_CA_LGD_CONFIG" (
	"LGD_CONFIG_ID" serial NOT NULL,
	"POPULATION_TYPE" varchar(100),
	"OBSERVATION_PERIOD" integer,
	"OBSERVATION_START_DATE" date,
	"OBSERVATION_END_DATE" date,
	"STATUS" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "FRS9_IMP_CA_PD_CONFIG" (
	"PD_CONFIG_ID" serial NOT NULL,
	"POPULATION_TYPE" varchar(100),
	"OBSERVATION_PERIOD" integer,
	"OBSERVATION_START_DATE" date,
	"OBSERVATION_END_DATE" date,
	"STATUS" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_amort_journal_data" (
	"id" bigserial NOT NULL,
	"prc_date" date,
	"account_id" bigint,
	"facno" varchar(50),
	"cifno" varchar(50),
	"acctno" varchar(70),
	"datasource" varchar(20),
	"prdtype" varchar(20),
	"prdcode" varchar(20),
	"trxcode" varchar(20),
	"ccy" varchar(10),
	"journalcode" varchar(20),
	"journalcode2" varchar(10),
	"status" varchar(20),
	"reverse" varchar(3),
	"flag_cf" varchar(3),
	"drcr" varchar(2),
	"glno" varchar(20),
	"n_amount" numeric(32, 6),
	"n_amount_idr" numeric(32, 6),
	"sourceprocess" varchar(20),
	"intmid" bigint,
	"branch" varchar(20),
	"noref" varchar(20),
	"valctr_code" varchar(50),
	"journal_desc" varchar(200),
	"createddate" timestamp,
	"createdby" varchar(30),
	"gl_internal_code" varchar(100),
	"method" varchar(10),
	"reserved_varchar_1" varchar(100),
	"reserved_varchar_2" varchar(100),
	"reserved_varchar_3" varchar(100),
	"gl_costcenter" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "frs9_default" (
	"prc_date" date,
	"account_id" bigint,
	"rule_id" bigint,
	"os_at_default" numeric(32, 6),
	"eqv_at_default" numeric(32, 6),
	"eir_at_default" double precision,
	"createdby" varchar(100),
	"createddate" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "frs9_ecl_model_mapping" (
	"pkid" smallint GENERATED ALWAYS AS IDENTITY (sequence name "frs9_ecl_model_mapping_pkid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"ecl_model_id" smallint,
	"eff_date" date,
	"pf_segment_id" smallint,
	"pf_segment_name" varchar(36),
	"pd_model_id" smallint,
	"lgd_model_id" smallint,
	"ead_model_id" smallint,
	"ccf_model_id" smallint,
	"pp_model_id" smallint,
	"lt_model_id" smallint
);
--> statement-breakpoint
CREATE TABLE "frs9_eir_ecf" (
	"id" bigserial NOT NULL,
	"account_id" bigint,
	"prc_date" date,
	"n_loan_amt" numeric(32, 6),
	"n_int_rate" double precision,
	"n_eff_int_rate" double precision,
	"startamortdate" date,
	"endamortdate" date,
	"gracedate" date,
	"disb_percentage" double precision,
	"disb_amount" numeric(32, 6),
	"plafond" numeric(32, 6),
	"paymentcode" varchar(3),
	"intcalccode" varchar(3),
	"paymentterm" varchar(3),
	"isgrace" varchar(3),
	"billing_date" date,
	"prev_pmt_date" date,
	"pmt_date" date,
	"i_days" bigint,
	"i_days2" bigint,
	"counter_rest" bigint,
	"counter" integer,
	"prev_rest_balance" numeric(32, 6),
	"rest_balance" numeric(32, 6),
	"n_osprn_prev" numeric(32, 6),
	"n_osprn" numeric(32, 6),
	"n_installment" numeric(32, 6),
	"n_prn_payment" numeric(32, 6),
	"n_int_payment" numeric(32, 6),
	"n_accru_int" numeric(32, 6),
	"n_fairvalue_prev" numeric(32, 6),
	"n_eff_int_amt" numeric(32, 6),
	"n_fairvalue" numeric(32, 6),
	"n_unamort_amt_prev" numeric(32, 6),
	"n_amort_amt" numeric(32, 6),
	"n_unamort_amt" numeric(32, 6),
	"n_cost_unamort_amt_prev" numeric(32, 6),
	"n_cost_amort_amt" numeric(32, 6),
	"n_cost_unamort_amt" numeric(32, 6),
	"n_fee_unamort_amt_prev" numeric(32, 6),
	"n_fee_amort_amt" numeric(32, 6),
	"n_fee_unamort_amt" numeric(32, 6),
	"n_gain_loss_unamort_amt_prev" numeric(32, 6),
	"n_gain_loss_amort_amt" numeric(32, 6),
	"n_gain_loss_unamort_amt" numeric(32, 6),
	"amortstopdate" date,
	"amortstopmsg" varchar(50),
	"n_daily_amort_cost" numeric(32, 6),
	"n_daily_amort_fee" numeric(32, 6),
	"n_daily_gain_loss" numeric(32, 6),
	"n_eff_int_amt0" numeric(32, 6),
	"n_eff_int_rate0" double precision,
	"n_daily_int_adj_amt" numeric(32, 6),
	"n_int_adj_amt" numeric(32, 6),
	"sw_adj_cost" numeric(32, 6),
	"sw_adj_fee" numeric(32, 6),
	"npv_rate" numeric(14, 10),
	"npv_amount" numeric(32, 6),
	"nocf_osprn" numeric(32, 6),
	"nocf_osprn_prev" numeric(32, 6),
	"nocf_int_rate" double precision,
	"nocf_prn_payment" numeric(32, 6),
	"nocf_eff_int_amt" numeric(32, 6),
	"nocf_unamort_amt_prev" numeric(32, 6),
	"nocf_amort_amt" numeric(32, 6),
	"nocf_unamort_amt" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "frs9_event_changes" (
	"prc_date" timestamp,
	"account_id" bigint,
	"account_number" varchar(70),
	"effective_date" timestamp,
	"before_value" varchar(100),
	"after_value" varchar(100),
	"event_id" bigint,
	"remarks" varchar(100),
	"createdby" varchar(50),
	"created_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_account_event" (
	"prc_date" date,
	"account_id" bigint,
	"event_id" smallint,
	"old_value" varchar(100),
	"new_value" varchar(100),
	"remarks" varchar(100),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_account_event_prv" (
	"prc_date" date,
	"account_id" bigint NOT NULL,
	"event_id" smallint,
	"old_value" varchar(100),
	"new_value" varchar(100),
	"remarks" varchar(100),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_ead" (
	"prc_date" date,
	"account_id" bigint,
	"account_number" varchar(50),
	"mob" smallint,
	"idays" smallint,
	"payment_date" date,
	"os_balance" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6),
	"installment" numeric(32, 6),
	"next_interest" numeric(32, 6),
	"ead_amt" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_ead_config" (
	"pkid" "smallserial" NOT NULL,
	"ead_model_name" varchar(250),
	"segment_id" smallint,
	"ead_method" varchar(10),
	"calc_method" varchar(10),
	"active_flag" boolean NOT NULL,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_ead_paym_avg" (
	"prc_date" date,
	"segment_id" bigint,
	"tenor" smallint,
	"counter" smallint,
	"paym_avg" double precision,
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_ecl_configd" (
	"pkid" "smallserial" NOT NULL,
	"ecl_model_id" smallint,
	"pf_segment_id" smallint,
	"stage_rule_id" smallint,
	"pd_model_id" smallint,
	"lgd_model_id" smallint,
	"ead_model_id" smallint,
	"overlay_rate" smallint DEFAULT 100,
	"period_type" smallint,
	"period_date" date,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_ecl_configh" (
	"pkid" "smallserial" NOT NULL,
	"ecl_model_name" varchar(50),
	"module" varchar(10),
	"effective_date" date NOT NULL,
	"active_flag" boolean NOT NULL,
	"last_run_period" date,
	"last_run_status" varchar(50),
	"last_run_date" timestamp,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_ecl_detail" (
	"prc_date" date,
	"account_id" bigint NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"start_date" date,
	"maturity_date" date,
	"branch_code" varchar(50),
	"prd_code" varchar(20),
	"remaining_tenor" smallint,
	"expected_life" smallint,
	"interest_rate" double precision,
	"eff_interest_rate" double precision,
	"outstanding" numeric(32, 6),
	"unused_amt" numeric(32, 6),
	"accrued_interest" numeric(32, 6),
	"installment_amt" numeric(32, 6),
	"impaired_flag" boolean,
	"dpd" smallint,
	"collectability" smallint,
	"internal_rating_code" varchar(5),
	"stage" varchar(5),
	"bucket_id" smallint,
	"ecl_model_id" smallint NOT NULL,
	"segment_id" smallint,
	"ecl_amt_ca_onbs" numeric(38, 6),
	"ecl_amt_ca_offbs" numeric(38, 6)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_ecl_sum" (
	"prc_date" date,
	"ecl_model_id" smallint NOT NULL,
	"segment_id" smallint,
	"branch_code" varchar(50),
	"prd_code" varchar(20),
	"stage" varchar(5),
	"bucket_id" smallint,
	"impaired_flag" boolean,
	"outstanding" numeric(38, 6),
	"unused_amt" numeric(38, 6),
	"accrued_interest" numeric(38, 6),
	"ecl_amt_ca_onbs" numeric(38, 6),
	"ecl_amt_ca_offbs" numeric(38, 6)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_ecl_ts" (
	"prc_date" date,
	"account_id" bigint,
	"account_number" varchar(50),
	"ecl_model_id" smallint NOT NULL,
	"segment_id" smallint,
	"payment_date" date,
	"mob" smallint,
	"os_balance" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6),
	"next_interest" numeric(32, 6),
	"ead_onbs" numeric(32, 6),
	"ead_offbs" numeric(32, 6),
	"pd_rate" double precision,
	"lgd_rate" double precision,
	"ccf_rate" double precision,
	"prepayment_rate" double precision,
	"discount_rate" double precision,
	"ecl_amt_ca_onbs" numeric(32, 6),
	"ecl_amt_ca_offbs" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_fl_scalard" (
	"pkid" "smallserial" NOT NULL,
	"scalar_id" smallint,
	"period" smallint,
	"weighted_scalar" double precision,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_fl_scalarh" (
	"pkid" "smallserial" NOT NULL,
	"scalar_name" varchar(30),
	"active_flag" boolean NOT NULL,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_lgd" (
	"pkid" smallint GENERATED ALWAYS AS IDENTITY (sequence name "frs9_imp_ca_lgd_pkid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"prc_date" date,
	"lgd_model_id" smallint,
	"lgd_model_name" varchar(100),
	"os_default" numeric(32, 6),
	"eqv_os_default" numeric(32, 6),
	"recovery_amt" numeric(32, 6),
	"eqv_recovery_amt" numeric(32, 6),
	"pv_recovery_amt" numeric(32, 6),
	"pv_eqv_recovery_amt" numeric(32, 6),
	"recovery_rate" double precision,
	"lgd_rate" double precision
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_lgd_coll_data" (
	"prc_date" date,
	"pv_date" date,
	"account_id" bigint,
	"sold_flag" boolean,
	"colla_amt" numeric(32, 6),
	"sell_amt" numeric(32, 6),
	"createdby" varchar(100),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_lgd_config" (
	"pkid" "smallserial" NOT NULL,
	"lgd_model_name" varchar(250),
	"segment_id" bigint,
	"lgd_method" bigint,
	"population_type" varchar(10),
	"observation_period" varchar(50),
	"observation_start_date" date,
	"workout_period" integer,
	"fl_flag" boolean NOT NULL,
	"fl_scalar_id" smallint,
	"lgd_rate" double precision,
	"active_flag" boolean,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_lgd_d" (
	"prc_date" date,
	"lgd_config_id" bigint,
	"lgd_method" bigint,
	"account_id" bigint,
	"eqv_os" numeric(32, 6),
	"eqv_rec" numeric(32, 6),
	"npv_eqv_rec" numeric(32, 6),
	"rec_rate" double precision,
	"lgd" double precision,
	"createdby" varchar(100),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_lgd_data" (
	"prc_date" date,
	"lgd_config_id" bigint,
	"lgd_method" bigint,
	"account_id" bigint,
	"eqv_at_default" numeric(32, 6),
	"wo_date" date,
	"closed_date" date,
	"account_status" char(1),
	"eqv_wo" numeric(32, 6),
	"eir_at_default" double precision,
	"createdby" varchar(36),
	"createddate" timestamp,
	"updatedby" varchar(100),
	"updateddate" timestamp,
	"repo_date" date,
	"eqv_repo" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_lgd_h" (
	"prc_date" date,
	"lgd_config_id" bigint,
	"lgd_method" bigint,
	"model_id" bigint,
	"eqv_os" numeric(32, 6),
	"eqv_rec" numeric(32, 6),
	"npv_eqv_rec" numeric(32, 6),
	"rec_rate" double precision,
	"lgd" double precision,
	"createdby" varchar(100),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_lgd_rec_d" (
	"prc_date" date,
	"lgd_config_id" bigint,
	"lgd_method" bigint,
	"account_id" bigint,
	"eqv_os" numeric(32, 6),
	"eir" double precision,
	"seq" smallint,
	"eqv_rec" numeric(32, 6),
	"npv_eqv_rec" numeric(32, 6),
	"createdby" varchar(100),
	"createddate" timestamp,
	"rn" integer
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_lgd_rec_data" (
	"prc_date" date,
	"default_rule_id" bigint,
	"account_id" bigint,
	"rec_os" numeric(32, 6),
	"eqv_rec_os" numeric(32, 6),
	"createdby" varchar(100),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_config" (
	"pkid" "smallserial" NOT NULL,
	"pd_model_name" varchar(250),
	"segment_id" smallint,
	"pd_method" varchar(10) NOT NULL,
	"interval" smallint NOT NULL,
	"population_type" varchar(10),
	"observation_period" smallint NOT NULL,
	"observation_start_date" date,
	"multiplication" smallint,
	"fl_flag" boolean,
	"fl_scalar_id" smallint,
	"ia_flag" boolean NOT NULL,
	"bucket_group" varchar(30),
	"active_flag" boolean NOT NULL,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_enr" (
	"prc_date" date NOT NULL,
	"base_date" date,
	"pd_config_id" bigint NOT NULL,
	"bucket_group" varchar(30),
	"bucket_from" smallint,
	"bucket_to" smallint,
	"calc_amount" numeric(32, 6),
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_flowrate" (
	"prc_date" date NOT NULL,
	"base_date" date,
	"pd_config_id" bigint NOT NULL,
	"bucket_group" varchar(30),
	"bucket_from" smallint,
	"bucket_to" smallint,
	"flowrate" double precision,
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_flowrate_avg" (
	"prc_date" date NOT NULL,
	"base_date" date,
	"pd_config_id" bigint NOT NULL,
	"bucket_group" varchar(30),
	"bucket_from" smallint,
	"bucket_to" smallint,
	"flowrate" double precision,
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_migration" (
	"prc_date" date NOT NULL,
	"base_date" date NOT NULL,
	"pd_config_id" bigint NOT NULL,
	"bucket_group" varchar(30),
	"account_id" bigint,
	"cif_number" varchar(50),
	"facility_number" varchar(50),
	"bucket_from" smallint,
	"bucket_to" smallint,
	"calc_amount" numeric(32, 6),
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_mmult" (
	"prc_date" date,
	"pd_config_id" bigint,
	"fl_seq" smallint,
	"bucket_group" varchar(30),
	"bucket_from" smallint,
	"bucket_to" smallint,
	"mmult" double precision,
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_odr" (
	"prc_date" date,
	"base_date" date,
	"pd_config_id" bigint,
	"tot_default" bigint,
	"non_default" bigint,
	"odr" double precision,
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_proxy" (
	"prc_date" date NOT NULL,
	"base_date" date,
	"pd_config_id" bigint NOT NULL,
	"bucket_group" varchar(50),
	"bucket_from" smallint,
	"bucket_to" smallint,
	"pd" double precision,
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_structure" (
	"prc_date" date,
	"pd_config_id" bigint,
	"pd_method" smallint,
	"scalar_id" bigint,
	"scenario_no" integer,
	"bucket_group" varchar(100),
	"bucket_id" integer,
	"fl_seq" integer,
	"fl_year" integer,
	"fl_month" integer,
	"pd_non_fl" double precision,
	"pd" double precision,
	"createddate" timestamp NOT NULL,
	"createdby" varchar(50),
	"weighted_scalar" double precision
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_pd_ts" (
	"pkid" smallint GENERATED ALWAYS AS IDENTITY (sequence name "frs9_imp_ca_pd_ts_pkid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"prc_date" date NOT NULL,
	"pd_model_id" smallint NOT NULL,
	"pd_model_name" varchar(100),
	"bucket_id" smallint,
	"pd_year" smallint,
	"pd_month" smallint,
	"pd_sequence" smallint,
	"pd_date" date,
	"pd_rate" double precision
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_result_d" (
	"prc_date" date,
	"account_id" bigint,
	"facility_number" varchar(100),
	"cif_number" varchar(100),
	"segment_id" bigint,
	"remaining_tenor" smallint,
	"start_date" date,
	"maturity_date" date,
	"default_flag" boolean,
	"dpd" smallint,
	"internal_rating_code" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_id" smallint,
	"ecl_model_id" bigint,
	"pd_config_id" bigint,
	"lgd_config_id" bigint,
	"ead_config_id" bigint,
	"ead_method" bigint,
	"bucket_group" varchar(30),
	"bucket_id" integer,
	"currency" varchar(5),
	"stage" smallint,
	"scenario_no" smallint,
	"fl_seq" smallint,
	"fl_year" smallint,
	"fl_motnh" smallint,
	"eir" double precision,
	"exchange_rate" numeric(32, 6),
	"outstanding" numeric(32, 6),
	"plafond" numeric(32, 6),
	"fib_amt" numeric(32, 6),
	"accrued_interest" numeric(32, 6),
	"unamort_cost_amt" numeric(32, 6),
	"unamort_fee_amt" numeric(32, 6),
	"ead_balance" numeric(32, 6),
	"paym_avg" double precision,
	"principal_amt" numeric(32, 6),
	"sum_principal_amt" numeric(32, 6),
	"next_interest" numeric(32, 6),
	"sum_next_interest" numeric(32, 6),
	"ead" numeric(32, 6),
	"pd" double precision,
	"lgd" double precision,
	"ecl_amount" numeric(32, 6),
	"probability" double precision,
	"ecl_weighted" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_result_d_prv" (
	"prc_date" date,
	"account_id" bigint,
	"facility_number" varchar(100),
	"cif_number" varchar(100),
	"segment_id" bigint,
	"remaining_tenor" smallint,
	"start_date" date,
	"maturity_date" date,
	"default_flag" boolean,
	"dpd" smallint,
	"internal_rating_code" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_id" smallint,
	"ecl_model_id" bigint,
	"pd_config_id" bigint,
	"lgd_config_id" bigint,
	"ead_config_id" bigint,
	"ead_method" bigint,
	"bucket_group" varchar(30),
	"bucket_id" integer,
	"currency" varchar(5),
	"stage" smallint,
	"scenario_no" smallint,
	"fl_seq" smallint,
	"fl_year" smallint,
	"fl_motnh" smallint,
	"eir" double precision,
	"exchange_rate" numeric(32, 6),
	"outstanding" numeric(32, 6),
	"plafond" numeric(32, 6),
	"fib_amt" numeric(32, 6),
	"accrued_interest" numeric(32, 6),
	"unamort_cost_amt" numeric(32, 6),
	"unamort_fee_amt" numeric(32, 6),
	"ead_balance" numeric(32, 6),
	"paym_avg" double precision,
	"principal_amt" numeric(32, 6),
	"sum_principal_amt" numeric(32, 6),
	"next_interest" numeric(32, 6),
	"sum_next_interest" numeric(32, 6),
	"ead" numeric(32, 6),
	"pd" double precision,
	"lgd" double precision,
	"ecl_amount" numeric(32, 6),
	"probability" double precision,
	"ecl_weighted" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_result_h" (
	"prc_date" date,
	"account_id" bigint,
	"facility_number" varchar(100),
	"cif_number" varchar(100),
	"segment_id" bigint,
	"remaining_tenor" smallint,
	"start_date" date,
	"maturity_date" date,
	"default_flag" boolean,
	"dpd" smallint,
	"internal_rating_code" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_id" smallint,
	"ecl_model_id" bigint,
	"pd_config_id" bigint,
	"lgd_config_id" bigint,
	"lgd" double precision,
	"ead_config_id" bigint,
	"ead_method" bigint,
	"bucket_group" varchar(30),
	"bucket_id" integer,
	"currency" varchar(5),
	"stage" smallint,
	"eir" double precision,
	"exchange_rate" numeric(32, 6),
	"outstanding" numeric(32, 6),
	"plafond" numeric(32, 6),
	"fib_amt" numeric(32, 6),
	"accrued_interest" numeric(32, 6),
	"unamort_cost_amt" numeric(32, 6),
	"unamort_fee_amt" numeric(32, 6),
	"ecl_amount" numeric(32, 6),
	"overlay_amount" numeric(32, 6),
	"ecl_final" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_result_h_prv" (
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"facility_number" varchar(100),
	"cif_number" varchar(100),
	"segment_id" bigint,
	"remaining_tenor" smallint,
	"start_date" date,
	"maturity_date" date,
	"default_flag" boolean,
	"dpd" smallint,
	"internal_rating_code" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_id" smallint,
	"ecl_model_id" bigint NOT NULL,
	"pd_config_id" bigint,
	"lgd_config_id" bigint,
	"lgd" double precision,
	"ead_config_id" bigint,
	"ead_method" bigint,
	"bucket_group" varchar(30),
	"bucket_id" integer,
	"currency" varchar(5),
	"stage" smallint,
	"eir" double precision,
	"exchange_rate" numeric(32, 6),
	"outstanding" numeric(32, 6),
	"plafond" numeric(32, 6),
	"fib_amt" numeric(32, 6),
	"accrued_interest" numeric(32, 6),
	"unamort_cost_amt" numeric(32, 6),
	"unamort_fee_amt" numeric(32, 6),
	"ecl_amount" numeric(32, 6),
	"overlay_amount" numeric(32, 6),
	"ecl_final" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_scenario_data" (
	"prc_date" date NOT NULL,
	"segment_id" integer NOT NULL,
	"segment_type" varchar(100),
	"account_id" bigint NOT NULL,
	"cif_number" varchar(50),
	"facility_number" varchar(50),
	"account_status" varchar(20),
	"currency" varchar(5),
	"dpd" smallint,
	"collectability" smallint,
	"internal_rating_code" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_id" smallint,
	"default_flag" boolean,
	"impaired_status" char(1),
	"tenor" smallint,
	"remaining_tenor" smallint,
	"payment_freq" smallint,
	"fix_principal_amt" numeric(32, 6),
	"plafond" numeric(32, 6),
	"outstanding" numeric(32, 6),
	"exchange_rate" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp,
	"createdhost" varchar(50),
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_schd" (
	"prc_date" date,
	"account_id" bigint,
	"account_number" varchar(50),
	"mob" smallint,
	"idays" smallint,
	"payment_date" date,
	"os_balance" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6),
	"next_interest" numeric(32, 6),
	"installment" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_schd_hist" (
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"account_number" varchar(50),
	"mob" smallint,
	"idays" smallint,
	"payment_date" date NOT NULL,
	"os_balance" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6),
	"next_interest" numeric(32, 6),
	"installment" numeric(33, 6),
	"end_prc_date" date,
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_schd_prv" (
	"prc_date" date,
	"account_id" bigint NOT NULL,
	"account_number" varchar(50),
	"mob" smallint,
	"idays" smallint,
	"payment_date" date NOT NULL,
	"os_balance" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6),
	"next_interest" numeric(32, 6),
	"installment" numeric(33, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ca_segment_query" (
	"segment_id" bigint NOT NULL,
	"group_segment" varchar(50),
	"sub_segment" varchar(50),
	"segment" varchar(50),
	"table_name" varchar(30),
	"condition" text,
	"segment_type" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ia_dcf" (
	"pkid" bigserial NOT NULL,
	"ia_id" bigint NOT NULL,
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"mob" bigint NOT NULL,
	"periode" date NOT NULL,
	"principal" numeric(32, 6) DEFAULT '0' NOT NULL,
	"interest" numeric(32, 6) DEFAULT '0' NOT NULL,
	"collateral" numeric(32, 6) DEFAULT '0' NOT NULL,
	"status" char(1) NOT NULL,
	"createdby" varchar(36) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(36) NOT NULL,
	"updatedby" varchar(36),
	"updateddate" timestamp,
	"updatedhost" varchar(30)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ia_detail" (
	"pkid" bigserial NOT NULL,
	"ia_id" bigint NOT NULL,
	"account_id" bigint NOT NULL,
	"eff_interest_rate" double precision NOT NULL,
	"mob" bigint NOT NULL,
	"periode" date NOT NULL,
	"principal" numeric(32, 6) DEFAULT '0' NOT NULL,
	"interest" numeric(32, 6) DEFAULT '0' NOT NULL,
	"installment" numeric(32, 6) DEFAULT '0' NOT NULL,
	"collateral" numeric(32, 6) DEFAULT '0' NOT NULL,
	"po_rate_1" double precision DEFAULT 0 NOT NULL,
	"rr_rate_1" double precision DEFAULT 0 NOT NULL,
	"default_1" numeric(32, 6) DEFAULT '0' NOT NULL,
	"po_rate_2" double precision DEFAULT 0 NOT NULL,
	"rr_rate_2" double precision DEFAULT 0 NOT NULL,
	"default_2" numeric(32, 6) DEFAULT '0' NOT NULL,
	"po_rate_3" double precision DEFAULT 0 NOT NULL,
	"rr_rate_3" double precision DEFAULT 0 NOT NULL,
	"default_3" numeric(32, 6) DEFAULT '0' NOT NULL,
	"pw_amt" numeric(32, 6) DEFAULT '0' NOT NULL,
	"discount_factor" double precision NOT NULL,
	"pv_amt" numeric(32, 6) DEFAULT '0' NOT NULL,
	"beginning_balance" numeric(32, 6) DEFAULT '0' NOT NULL,
	"eir_amt" numeric(32, 6) DEFAULT '0' NOT NULL,
	"ending_balance" numeric(32, 6) DEFAULT '0' NOT NULL,
	"createdby" varchar(36) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(36) NOT NULL,
	"updatedby" varchar(36),
	"updateddate" timestamp,
	"updatedhost" varchar(30)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ia_header" (
	"pkid" bigserial NOT NULL,
	"ia_id" bigint NOT NULL,
	"prc_date" date NOT NULL,
	"eff_date" date NOT NULL,
	"cif_number" varchar(50) NOT NULL,
	"cif_name" varchar(150) NOT NULL,
	"account_id" bigint NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"currency" varchar(5) NOT NULL,
	"eff_interest_rate" double precision NOT NULL,
	"interest_rate" double precision NOT NULL,
	"dpd" smallint,
	"collectability" smallint,
	"rating_code" varchar(5),
	"impaired_flag" char(1) NOT NULL,
	"method" varchar(20),
	"plafond" numeric(32, 6) DEFAULT '0' NOT NULL,
	"outstanding" numeric(32, 6) DEFAULT '0' NOT NULL,
	"accrued_interest" numeric(32, 6) DEFAULT '0' NOT NULL,
	"carrying_amt" numeric(32, 6) DEFAULT '0' NOT NULL,
	"ead_amt" numeric(32, 6) DEFAULT '0' NOT NULL,
	"pv_dcf_amt" numeric(32, 6) DEFAULT '0' NOT NULL,
	"ecl_ia_amt" numeric(32, 6) DEFAULT '0' NOT NULL,
	"trigger_remarks" varchar(1000),
	"trigger_filename" varchar(100),
	"scenario_id" smallint,
	"n_of_scenario" smallint,
	"po_rate_1" double precision DEFAULT 0 NOT NULL,
	"po_rate_2" double precision DEFAULT 0 NOT NULL,
	"po_rate_3" double precision DEFAULT 0 NOT NULL,
	"sc_name_1" varchar(20),
	"sc_name_2" varchar(20),
	"sc_name_3" varchar(20),
	"status" integer NOT NULL,
	"createdby" varchar(36) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(36) NOT NULL,
	"updatedby" varchar(36),
	"updateddate" timestamp,
	"updatedhost" varchar(30),
	"reviewedby" varchar(36),
	"revieweddate" timestamp,
	"reviewedhost" varchar(30)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ia_result_d" (
	"pkid" bigserial NOT NULL,
	"ia_id" bigint,
	"prc_date" date,
	"account_id" bigint,
	"mob" smallint,
	"periode" date,
	"principal" numeric(32, 6),
	"interest" numeric(32, 6),
	"installment" numeric(32, 6),
	"collateral" numeric(32, 6),
	"po_rate_1" double precision,
	"rr_rate_1" double precision,
	"default_1" numeric(32, 6),
	"po_rate_2" double precision,
	"rr_rate_2" double precision,
	"default_2" numeric(32, 6),
	"po_rate_3" double precision,
	"rr_rate_3" double precision,
	"default_3" numeric(32, 6),
	"pw_amt" numeric(32, 6),
	"discount_factor" double precision,
	"pv_amt" numeric(32, 6),
	"beginning_balance" numeric(32, 6),
	"eir_amt" numeric(32, 6),
	"ending_balance" numeric(32, 6),
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ia_result_h" (
	"pkid" bigserial NOT NULL,
	"ia_id" bigint,
	"prc_date" date,
	"account_id" bigint,
	"account_number" varchar(50),
	"cif_number" varchar(50),
	"cif_name" varchar(150),
	"currency" varchar(5),
	"dpd" smallint,
	"collectability" smallint,
	"rating_code" varchar(5),
	"interest_rate" double precision,
	"eff_interest_rate" double precision,
	"outstanding" numeric(32, 6),
	"accrued_interest" numeric(32, 6),
	"carrying_amt" numeric(32, 6),
	"ead_amt" numeric(32, 6),
	"pv_dcf_amt" numeric(32, 6),
	"ecl_ia_amt" numeric(32, 6),
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_ia_rr" (
	"pkid" bigserial NOT NULL,
	"ia_id" bigint NOT NULL,
	"account_id" bigint NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"rr_rate_1" double precision DEFAULT 0 NOT NULL,
	"rr_rate_2" double precision DEFAULT 0 NOT NULL,
	"rr_rate_3" double precision DEFAULT 0 NOT NULL,
	"createdby" varchar(36) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(36) NOT NULL,
	"updatedby" varchar(36),
	"updateddate" timestamp,
	"updatedhost" varchar(30)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_journal_data" (
	"id" bigserial NOT NULL,
	"prc_date" date,
	"account_id" bigint,
	"facility_number" varchar(50),
	"cif_number" varchar(50),
	"prdcode" varchar(50),
	"currency" varchar(5),
	"journalcode" varchar(50),
	"journalcode2" varchar(50),
	"reverse" boolean,
	"flag_cf" varchar(10),
	"dbcr" varchar(2),
	"gl_number" varchar(20),
	"n_amount" numeric(32, 6),
	"n_amount_idr" numeric(32, 6),
	"sourceprocess" varchar(50),
	"intmid" bigint,
	"branch" varchar(50),
	"noref" varchar(20),
	"valctr_code" varchar(50),
	"gl_desc" varchar(200),
	"gl_costcenter" varchar(20),
	"createddate" timestamp,
	"createdby" varchar(30)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_movement_data" (
	"prc_date" date,
	"urut" integer,
	"group_segment" varchar(100),
	"stage1" numeric(32, 6),
	"stage2" numeric(32, 6),
	"stage3" numeric(32, 6),
	"stage1_i" numeric(32, 6),
	"stage2_i" numeric(32, 6),
	"stage3_i" numeric(32, 6),
	"gca_stage1" numeric(32, 6),
	"gca_stage2" numeric(32, 6),
	"gca_stage3" numeric(32, 6),
	"gca_stage1_i" numeric(32, 6),
	"gca_stage2_i" numeric(32, 6),
	"gca_stage3_i" numeric(32, 6),
	"poci" numeric(32, 6),
	"createdby" varchar(36),
	"createddate" timestamp,
	"createdhost" varchar(30)
);
--> statement-breakpoint
CREATE TABLE "frs9_imp_nominative" (
	"pkid" bigserial NOT NULL,
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"data_source" varchar(50),
	"account_number" varchar(50),
	"facility_number" varchar(50),
	"cif_number" varchar(50),
	"cif_name" varchar(150),
	"start_date" date,
	"maturity_date" date,
	"outstanding" numeric(32, 6),
	"currency" varchar(5),
	"interest_rate" double precision,
	"dpd" smallint,
	"ext_rating" varchar(5),
	"tenor" smallint,
	"prd_code" varchar(20),
	"group_segment" varchar(50),
	"segment" varchar(50),
	"sub_segment" varchar(50),
	"rating_bucket" smallint,
	"lgd" double precision,
	"sicr" boolean,
	"stage" smallint,
	"ecl" numeric(32, 6),
	"ecl_coverage" double precision
);
--> statement-breakpoint
CREATE TABLE "frs9_master_account" (
	"pkid" bigserial NOT NULL,
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"facility_number" varchar(50),
	"cif_type" varchar(50),
	"cif_number" varchar(50),
	"cif_name" varchar(150),
	"account_status" varchar(20),
	"data_source" varchar(20),
	"prd_group" varchar(20),
	"prd_type" varchar(50),
	"prd_code" varchar(20),
	"gl_group" varchar(50),
	"branch_code" varchar(50),
	"tenor_org" smallint,
	"remaining_tenor" smallint,
	"start_date" date,
	"maturity_date" date,
	"start_amort_date" date,
	"end_amort_date" date,
	"paid_off_date" date,
	"write_off_date" date,
	"first_payment_date" date,
	"next_payment_date" date,
	"last_payment_date" date,
	"next_sch_prin_date" date,
	"next_sch_int_date" date,
	"grace_type" varchar(5),
	"grace_start_date" date,
	"grace_end_date" date,
	"market_rate" double precision,
	"interest_rate" double precision,
	"eff_interest_rate" double precision,
	"collectability" smallint,
	"collectability_group" smallint,
	"dpd" smallint,
	"dpd_group" smallint,
	"dpd_counter" smallint,
	"internal_rating_code_initial" varchar(5),
	"internal_rating_code" varchar(5),
	"ext_rating_id_initial" smallint,
	"ext_rating_code_initial" varchar(5),
	"ext_rating_agency_initial" varchar(5),
	"ext_rating_id" smallint,
	"ext_rating_code" varchar(5),
	"ext_rating_agency" varchar(5),
	"payment_code" varchar(20),
	"payment_term" varchar(2),
	"payment_freq" smallint,
	"int_pmt_term" varchar(2),
	"int_pmt_freq" smallint,
	"amortization_type" varchar(5),
	"pmt_sch_status" varchar(5),
	"eir_sch_status" varchar(5),
	"repo_flag" boolean,
	"revolving_flag" boolean,
	"bm_flag" boolean,
	"committed_flag" boolean,
	"npl_flag" boolean,
	"npl_date" date,
	"restructure_flag" boolean,
	"restructure_date" date,
	"restructure_review_date" date,
	"fib_flag" boolean,
	"fib_start_date" date,
	"fib_tenor" smallint,
	"fib_amt" numeric(32, 6) DEFAULT '0',
	"special_case_flag" boolean,
	"impaired_flag" boolean,
	"impaired_status" char(1),
	"segment_id" smallint,
	"group_segment" varchar(50),
	"segment" varchar(50),
	"sub_segment" varchar(50),
	"ecl_model_id" smallint,
	"ead_config_id" smallint,
	"pd_config_id" smallint,
	"lgd_config_id" smallint,
	"sicr_flag" boolean,
	"stage_original" varchar(5),
	"stage_override" varchar(5),
	"stage" varchar(5),
	"bucket_id_original" smallint,
	"bucket_id_override" smallint,
	"bucket_id" smallint,
	"bucket_id_obligor" smallint,
	"bucket_id_ed" smallint,
	"interest_base" varchar(2),
	"sppi_status" varchar(50),
	"bm_status" varchar(50),
	"asset_class" varchar(50),
	"currency" varchar(5),
	"exchange_rate" double precision,
	"plafond" numeric(32, 6) DEFAULT '0',
	"full_release_amt" numeric(32, 6) DEFAULT '0',
	"unused_amt" numeric(32, 6) DEFAULT '0',
	"outstanding" numeric(32, 6) DEFAULT '0',
	"outstanding_wo" numeric(32, 6) DEFAULT '0',
	"accrued_interest" numeric(32, 6) DEFAULT '0',
	"installment_amt" numeric(32, 6) DEFAULT '0',
	"fix_principal_amt" numeric(32, 6) DEFAULT '0',
	"fix_interest_amt" numeric(32, 6) DEFAULT '0',
	"initial_fee_amt" numeric(32, 6) DEFAULT '0',
	"unamort_fee_amt" numeric(32, 6) DEFAULT '0',
	"amort_fee_amt" numeric(32, 6) DEFAULT '0',
	"initial_cost_amt" numeric(32, 6) DEFAULT '0',
	"unamort_cost_amt" numeric(32, 6) DEFAULT '0',
	"amort_cost_amt" numeric(32, 6) DEFAULT '0',
	"initial_bm_amt" numeric(32, 6) DEFAULT '0',
	"unamort_bm_amt" numeric(32, 6) DEFAULT '0',
	"amort_bm_amt" numeric(32, 6) DEFAULT '0',
	"initial_gainloss_amt" numeric(32, 6) DEFAULT '0',
	"unamort_gainloss_amt" numeric(32, 6) DEFAULT '0',
	"amort_gainloss_amt" numeric(32, 6) DEFAULT '0',
	"carrying_amt" numeric(32, 6) DEFAULT '0',
	"fair_value_amt" numeric(32, 6) DEFAULT '0',
	"ecl_ca_onbs_amt" numeric(32, 6) DEFAULT '0',
	"ecl_ca_offbs_amt" numeric(32, 6) DEFAULT '0',
	"ecl_ia_onbs_amt" numeric(32, 6) DEFAULT '0',
	"ecl_overlay_amt" numeric(32, 6) DEFAULT '0',
	"ecl_final_amt" numeric(32, 6) DEFAULT '0',
	"unwinding_ca_amt" numeric(32, 6) DEFAULT '0',
	"unwinding_ia_amt" numeric(32, 6) DEFAULT '0',
	"unwinding_ia_sum_amt" numeric(32, 6) DEFAULT '0',
	"ecl_beginning_balance" numeric(32, 6) DEFAULT '0',
	"ecl_charge" numeric(32, 6) DEFAULT '0',
	"ecl_writeback" numeric(32, 6) DEFAULT '0',
	"ecl_ending_balance" numeric(32, 6) DEFAULT '0',
	"lgd" double precision,
	"weighted_eff_interest_rate" double precision,
	"weighted_interest_rate" double precision
);
--> statement-breakpoint
CREATE TABLE "frs9_master_account_repo" (
	"prc_date" date NOT NULL,
	"repo_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"cif_number" varchar(50),
	"facility_number" varchar(50),
	"outstanding_repo" numeric(32, 6),
	"eqv_os_repo" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "frs9_master_account_wo" (
	"prc_date" date,
	"wo_date" date,
	"account_id" bigint NOT NULL,
	"cif_number" varchar(50),
	"facility_number" varchar(50),
	"outstanding_wo" numeric(32, 6),
	"eqv_os_wo" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "frs9_master_exchange_rate" (
	"prc_date" date,
	"currency" varchar(5),
	"exchange_rate" numeric(32, 6),
	"createdby" varchar(100),
	"createddate" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "frs9_master_transaction_cost" (
	"prc_date" date,
	"account_id" bigint NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"effective_date" date,
	"data_source" varchar(20),
	"prd_type" varchar(20),
	"prd_code" varchar(20),
	"branch_code" varchar(20),
	"debet_credit_flag" char(1),
	"currency_code" varchar(5),
	"fee_cost_id" varchar(1) NOT NULL,
	"trx_code" varchar(20),
	"org_ccy_amt" numeric(32, 6),
	"eqv_lcy_amt" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_bucketd" (
	"pkid" "smallserial" NOT NULL,
	"pkid_header" smallint,
	"bucket_id" smallint,
	"bucket_name" varchar(100),
	"range_start" smallint,
	"range_end" smallint,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_bucketh" (
	"pkid" "smallserial" NOT NULL,
	"bucket_group" varchar(30),
	"bucket_desc" varchar(255),
	"basis" varchar(20),
	"bucket_default" smallint,
	"closed_flag" boolean NOT NULL,
	"wo_flag" boolean NOT NULL,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_commond" (
	"pkid" bigserial NOT NULL,
	"param_code" varchar(50) NOT NULL,
	"param_seq" integer NOT NULL,
	"value1" varchar(100) NOT NULL,
	"value2" varchar(100) NOT NULL,
	"value3" varchar(50) NOT NULL,
	"paramdesc" varchar(1000) NOT NULL,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_commonh" (
	"pkid" bigserial NOT NULL,
	"param_code" varchar(10),
	"param_name" varchar(255),
	"param_usage" varchar(255),
	"param_type" varchar(10),
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50),
	"banking_type" varchar(20) DEFAULT 'conventional',
	"is_active" boolean DEFAULT true,
	"requires_approval" boolean DEFAULT false,
	CONSTRAINT "chk_banking_type" CHECK ((banking_type)::text = ANY (ARRAY[('conventional'::character varying)::text, ('syariah'::character varying)::text, ('dual'::character varying)::text]))
);
--> statement-breakpoint
CREATE TABLE "frs9_param_journal" (
	"pkid" "smallserial" NOT NULL,
	"gl_group" varchar(20),
	"currency" char(3),
	"gl_type" varchar(20),
	"gl_code" varchar(20),
	"gl_number" varchar(20),
	"dbcr" char(1),
	"gl_desc" varchar(255),
	"active_flag" boolean,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_product" (
	"pkid" "smallserial" NOT NULL,
	"data_source" varchar(20) NOT NULL,
	"prd_group" varchar(20) NOT NULL,
	"prd_type" varchar(20) NOT NULL,
	"prd_code" varchar(20) NOT NULL,
	"prd_desc" varchar(255) NOT NULL,
	"currency" varchar(5) NOT NULL,
	"amortization_type" varchar(10),
	"al_flag" varchar(1),
	"impaired_flag" boolean,
	"bm_flag" boolean,
	"expected_life" integer,
	"borrowing_rate" double precision,
	"market_rate" double precision,
	"active_flag" boolean NOT NULL,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_scenario_rulesd" (
	"pkid" "smallserial" NOT NULL,
	"rule_id" smallint,
	"query_group" smallint,
	"seq" smallint,
	"table_name" varchar(30) NOT NULL,
	"column_name" varchar(30) NOT NULL,
	"data_type" varchar(15) NOT NULL,
	"operator" varchar(10),
	"value1" text NOT NULL,
	"value2" text,
	"condition" varchar(3),
	"detail_type" varchar(50),
	"stage_from" varchar(2),
	"stage_to" varchar(2),
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_scenario_rulesh" (
	"pkid" "smallserial" NOT NULL,
	"rule_name" varchar(250) NOT NULL,
	"rule_type" varchar(50) NOT NULL,
	"updated_table" varchar(30),
	"updated_column" varchar(30),
	"value" varchar(250),
	"seq" smallint,
	"active_flag" boolean,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_segmentd" (
	"pkid" "smallserial" NOT NULL,
	"segment_id" smallint,
	"query_group" smallint,
	"seq" smallint,
	"table_name" varchar(30),
	"column_name" varchar(30),
	"data_type" varchar(15),
	"operator" varchar(10),
	"value1" text,
	"value2" text,
	"condition" varchar(3),
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_param_segmenth" (
	"pkid" "smallserial" NOT NULL,
	"group_segment" varchar(150),
	"segment" varchar(150),
	"sub_segment" varchar(150),
	"segment_type" varchar(50),
	"seq" smallint,
	"active_flag" boolean,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_prc_date" (
	"pkid" smallint GENERATED ALWAYS AS IDENTITY (sequence name "frs9_prc_date_pkid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"currdate" date NOT NULL,
	"prevdate" date,
	"batch_status" varchar(50),
	"remark" varchar(250),
	"last_process_date" date,
	"sessionid" varchar(50),
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "frs9_r_model_summary" (
	"model_id" serial NOT NULL,
	"model_name" varchar(255),
	"model_status" varchar(50),
	"dependent_variable" varchar(100),
	"r_squared" numeric(10, 4),
	"mape" numeric(10, 4),
	"created_date" timestamp DEFAULT CURRENT_TIMESTAMP,
	"data_file" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "frs9_statistic" (
	"pkid" bigint GENERATED ALWAYS AS IDENTITY (sequence name "frs9_statistic_pkid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"prc_date" date,
	"sp_name" varchar(100),
	"start_date" timestamp,
	"end_date" timestamp,
	"counter" bigint,
	"sessionid" varchar(100),
	"iscomplete" varchar(2),
	"prc_name" varchar(100),
	"prc_process_time" varchar(30),
	"session_process_time" varchar(30),
	"remark" varchar(250),
	"parameter" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "stg_frs9_master_account_bpf" (
	"prc_date" date,
	"account_number" varchar(50),
	"facility_number" varchar(50),
	"cif_number" varchar(50),
	"cif_name" varchar(150),
	"account_status" varchar(20),
	"data_source" varchar(20),
	"prd_group" varchar(20),
	"prd_type" varchar(50),
	"prd_code" varchar(20),
	"branch_code" varchar(50),
	"tenor_org" smallint,
	"start_date" date,
	"maturity_date" date,
	"paid_off_date" date,
	"write_off_date" date,
	"first_payment_date" date,
	"next_payment_date" date,
	"last_payment_date" date,
	"grace_type" varchar(5),
	"grace_start_date" date,
	"grace_end_date" date,
	"interest_rate" double precision,
	"eff_interest_rate" double precision,
	"collectability" smallint,
	"dpd" integer,
	"ext_rating_code_initial" varchar(5),
	"ext_rating_agency_initial" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_agency" varchar(5),
	"payment_code" varchar(20),
	"payment_term" varchar(2),
	"payment_freq" smallint,
	"int_pmt_term" varchar(2),
	"int_pmt_freq" smallint,
	"npl_flag" boolean,
	"npl_date" date,
	"restructure_flag" boolean,
	"restructure_date" date,
	"restructure_review_date" date,
	"group_segment" varchar(50),
	"segment" varchar(50),
	"sub_segment" varchar(50),
	"interest_base" varchar(2),
	"asset_class" varchar(50),
	"currency" varchar(5),
	"exchange_rate" numeric(32, 6),
	"plafond" numeric(32, 6),
	"unused_amt" numeric(32, 6),
	"outstanding" numeric(32, 6),
	"outstanding_wo" numeric(32, 6),
	"accrued_interest" numeric(32, 6),
	"installment_amt" numeric(32, 6),
	"fix_principal_amt" numeric(32, 6),
	"fix_interest_amt" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "stg_master_loan" (
	"download_date" timestamp,
	"account_no_core" varchar(255),
	"account_no" varchar(255),
	"segment" varchar(255),
	"bucket_ori" double precision,
	"bucket_cap" double precision,
	"bucket_pre_rest" double precision,
	"bucket_final" double precision,
	"stage" double precision,
	"start_date" timestamp,
	"maturity_date" timestamp,
	"adjusted_maturity_date" timestamp,
	"grace_start_date" timestamp,
	"grace_end_date" timestamp,
	"grace_flag" varchar(255),
	"grace_period_months" double precision,
	"watchlist_flag" varchar(255),
	"restru_flag" varchar(255),
	"restructure_date" timestamp,
	"next_restru_instalment_date" timestamp,
	"os_balance" double precision,
	"os_principal" double precision,
	"instalment_amount" double precision,
	"effective_rate_percent" double precision,
	"lgd_percent" double precision,
	"tenor" double precision,
	"remaining_tenor" double precision,
	"undrawn" double precision,
	"asset_type" varchar(255),
	"asset_condition" varchar(255),
	"branch" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "stg_paym_schd" (
	"prc_date" date NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"idays" smallint,
	"payment_date" date,
	"os_balance" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6),
	"installment" numeric(33, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tblu_master_collateral" (
	"pkid" "smallserial" NOT NULL,
	"prc_date" date NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"collateral_description" varchar(100),
	"collateral_value" numeric(32, 6) DEFAULT '0',
	"selling_date" date,
	"selling_price" numeric(32, 6),
	"workout_period" smallint,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "tblu_master_pd_proxy" (
	"pkid" "smallserial" NOT NULL,
	"prc_date" date NOT NULL,
	"rating_agency" varchar(20) NOT NULL,
	"rating_from" varchar(10) NOT NULL,
	"rating_to" varchar(10) NOT NULL,
	"pd_rate" double precision NOT NULL,
	"createdby" varchar(50) NOT NULL,
	"createddate" timestamp NOT NULL,
	"createdhost" varchar(50) NOT NULL,
	"updatedby" varchar(50),
	"updateddate" timestamp,
	"updatedhost" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "tblu_paym_schd" (
	"prc_date" date NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"idays" smallint,
	"payment_date" date,
	"os_balance" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6),
	"installment" numeric(33, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_fma_preview" (
	"pkid" bigint NOT NULL,
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"account_number" varchar(50) NOT NULL,
	"facility_number" varchar(50),
	"cif_type" varchar(50),
	"cif_number" varchar(50),
	"cif_name" varchar(150),
	"account_status" varchar(20),
	"data_source" varchar(20),
	"prd_group" varchar(20),
	"prd_type" varchar(50),
	"prd_code" varchar(20),
	"gl_group" varchar(50),
	"branch_code" varchar(50),
	"tenor_org" smallint,
	"remaining_tenor" smallint,
	"start_date" date,
	"maturity_date" date,
	"start_amort_date" date,
	"end_amort_date" date,
	"paid_off_date" date,
	"write_off_date" date,
	"first_payment_date" date,
	"next_payment_date" date,
	"last_payment_date" date,
	"next_sch_prin_date" date,
	"next_sch_int_date" date,
	"grace_type" varchar(5),
	"grace_start_date" date,
	"grace_end_date" date,
	"market_rate" double precision,
	"interest_rate" double precision,
	"eff_interest_rate" double precision,
	"collectability" smallint,
	"collectability_group" smallint,
	"dpd" smallint,
	"dpd_group" smallint,
	"internal_rating_code" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_agency" varchar(5),
	"payment_code" varchar(20),
	"payment_term" varchar(2),
	"payment_freq" smallint,
	"int_pmt_term" varchar(2),
	"int_pmt_freq" smallint,
	"pmt_sch_status" char(1),
	"eir_sch_status" char(1),
	"revolving_flag" boolean,
	"bm_flag" boolean,
	"committed_flag" boolean,
	"npl_flag" boolean,
	"npl_date" date,
	"restructure_flag" boolean,
	"restructure_date" date,
	"restructure_review_date" date,
	"repo_flag" boolean,
	"fib_flag" boolean,
	"fib_start_date" date,
	"fib_tenor" smallint,
	"fib_amt" numeric(32, 6) DEFAULT '0',
	"special_case_flag" boolean,
	"impaired_flag" boolean,
	"impaired_status" char(1),
	"segment_id" smallint,
	"group_segment" varchar(50),
	"segment" varchar(50),
	"sub_segment" varchar(50),
	"sicr_flag" boolean,
	"stage" varchar(5),
	"bucket_id" smallint,
	"bucket_id_obligor" smallint,
	"bucket_id_ed" smallint,
	"ecl_model_id" bigint,
	"ead_config_id" bigint,
	"pd_config_id" bigint,
	"lgd_config_id" bigint,
	"lgd" double precision DEFAULT 0,
	"interest_base" varchar(2),
	"sppi_status" varchar(50),
	"bm_status" varchar(50),
	"asset_class" varchar(50),
	"currency" varchar(5),
	"exchange_rate" double precision,
	"plafond" numeric(32, 6) DEFAULT '0',
	"full_release_amt" numeric(32, 6) DEFAULT '0',
	"unused_amt" numeric(32, 6) DEFAULT '0',
	"outstanding" numeric(32, 6) DEFAULT '0',
	"outstanding_wo" numeric(32, 6) DEFAULT '0',
	"accrued_interest" numeric(32, 6) DEFAULT '0',
	"installment_amt" numeric(32, 6) DEFAULT '0',
	"fix_principal_amt" numeric(32, 6) DEFAULT '0',
	"fix_interest_amt" numeric(32, 6) DEFAULT '0',
	"initial_fee_amt" numeric(32, 6) DEFAULT '0',
	"unamort_fee_amt" numeric(32, 6) DEFAULT '0',
	"amort_fee_amt" numeric(32, 6) DEFAULT '0',
	"initial_cost_amt" numeric(32, 6) DEFAULT '0',
	"unamort_cost_amt" numeric(32, 6) DEFAULT '0',
	"amort_cost_amt" numeric(32, 6) DEFAULT '0',
	"initial_bm_amt" numeric(32, 6) DEFAULT '0',
	"unamort_bm_amt" numeric(32, 6) DEFAULT '0',
	"amort_bm_amt" numeric(32, 6) DEFAULT '0',
	"carrying_amt" numeric(32, 6) DEFAULT '0',
	"ecl_ca_onbs_amt" numeric(32, 6) DEFAULT '0',
	"ecl_ca_offbs_amt" numeric(32, 6) DEFAULT '0',
	"ecl_ia_onbs_amt" numeric(32, 6) DEFAULT '0',
	"ecl_final_amt" numeric(32, 6) DEFAULT '0',
	"unwinding_ca_amt" numeric(32, 6) DEFAULT '0',
	"unwinding_ia_amt" numeric(32, 6) DEFAULT '0',
	"unwinding_ia_sum_amt" numeric(32, 6),
	"ecl_beginning_balance" numeric(32, 6) DEFAULT '0',
	"ecl_charge" numeric(32, 6) DEFAULT '0',
	"ecl_writeback" numeric(32, 6) DEFAULT '0',
	"ecl_ending_balance" numeric(32, 6) DEFAULT '0',
	"dpd_counter" smallint,
	"internal_rating_code_initial" varchar(5),
	"ext_rating_id_initial" smallint,
	"ext_rating_code_initial" varchar(5),
	"ext_rating_agency_initial" varchar(5),
	"ext_rating_id" smallint,
	"amortization_type" varchar(5),
	"stage_original" varchar(5),
	"stage_override" varchar(5),
	"bucket_id_original" smallint,
	"bucket_id_override" smallint,
	"initial_gainloss_amt" numeric(32, 6),
	"unamort_gainloss_amt" numeric(32, 6),
	"amort_gainloss_amt" numeric(32, 6),
	"fair_value_amt" numeric(32, 6),
	"ecl_overlay_amt" numeric(32, 6),
	"weighted_eff_interest_rate" double precision,
	"weighted_interest_rate" double precision
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_ecl_fma" (
	"pkid" bigserial NOT NULL,
	"prc_date" date,
	"account_id" bigint,
	"account_number" varchar(50),
	"facility_number" varchar(100),
	"cif_number" varchar(100),
	"segment_id" bigint,
	"remaining_tenor" smallint,
	"start_date" date,
	"maturity_date" date,
	"next_payment_date" date,
	"next_sch_prin_date" date,
	"next_sch_int_date" date,
	"grace_type" varchar(5),
	"grace_start_date" date,
	"grace_end_date" date,
	"fib_flag" boolean,
	"fib_start_date" date,
	"fib_tenor" smallint,
	"payment_code" varchar(20),
	"payment_term" varchar(2),
	"payment_freq" integer,
	"int_pmt_term" varchar(2),
	"int_pmt_freq" integer,
	"default_flag" boolean,
	"dpd" integer,
	"internal_rating_code" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_id" smallint,
	"ecl_model_id" bigint,
	"pd_config_id" bigint,
	"lgd_config_id" bigint,
	"ead_config_id" bigint,
	"ead_method" bigint,
	"ead_calc_method" bigint,
	"bucket_group" varchar(30),
	"bucket_id" integer,
	"currency" varchar(5),
	"stage" smallint,
	"interest_base" varchar(2),
	"interest_rate" double precision,
	"eir" double precision,
	"exchange_rate" numeric(32, 6),
	"installment_amt" numeric(32, 6),
	"fix_principal_amt" numeric(32, 6),
	"fix_interest_amt" numeric(32, 6),
	"outstanding" numeric(32, 6),
	"plafond" numeric(32, 6),
	"fib_amt" numeric(32, 6),
	"accrued_interest" numeric(32, 6),
	"unamort_cost_amt" numeric(32, 6),
	"unamort_fee_amt" numeric(32, 6),
	"ead_balance" numeric(32, 6),
	"beginning_balance" numeric(32, 6),
	"ecl_amount" numeric(32, 6),
	"ia_unwinding_amount" numeric(32, 6),
	"ia_unwinding_sum_amount" numeric(32, 6),
	"writeback_amount" numeric(32, 6),
	"charge_amount" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_ead_paym_avg" (
	"prc_date" date,
	"segment_id" bigint,
	"tenor" smallint,
	"counter" smallint,
	"paym_avg" double precision,
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_lgd_rec_d" (
	"prc_date" date,
	"lgd_config_id" bigint,
	"lgd_method" bigint,
	"account_id" bigint,
	"eqv_os" numeric(32, 6),
	"eir" double precision,
	"seq" smallint,
	"eqv_rec" numeric(32, 6),
	"npv_eqv_rec" numeric(32, 6),
	"createdby" varchar(100),
	"createddate" timestamp,
	"rn" integer
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_pd_data" (
	"prc_date" date,
	"pd_config_id" bigint,
	"pd_method" smallint,
	"account_id" bigint,
	"account_status" char(1),
	"cif_number" varchar(50),
	"facility_number" varchar(50),
	"currency" varchar(5),
	"bucket_default" smallint,
	"include_closed_flag" boolean,
	"include_wo_flag" boolean,
	"bucket_group" varchar(30),
	"bucket_id" smallint,
	"dpd" smallint,
	"collectability" smallint,
	"internal_rating_code" varchar(5),
	"ext_rating_code" varchar(5),
	"ext_rating_id" smallint,
	"default_flag" boolean,
	"wo_flag" boolean,
	"remaining_tenor" smallint,
	"plafond" numeric(32, 6),
	"outstanding" numeric(32, 6),
	"createdby" varchar(50),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_pd_scn_curr" (
	"period" date NOT NULL,
	"pd_config_id" bigint NOT NULL,
	"bucket_group" varchar(30),
	"account_id" bigint,
	"account_status" char(1),
	"cif_number" varchar(50),
	"facility_number" varchar(50),
	"bucket_id" smallint,
	"calc_amount" numeric(32, 6),
	"wo_flag" boolean,
	"include_wo_flag" boolean,
	"include_closed_flag" boolean,
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_pd_scn_prev" (
	"period" date NOT NULL,
	"pd_config_id" bigint NOT NULL,
	"bucket_group" varchar(30),
	"account_id" bigint,
	"account_status" char(1),
	"cif_number" varchar(50),
	"facility_number" varchar(50),
	"bucket_id" smallint,
	"calc_amount" numeric(32, 6),
	"wo_flag" boolean,
	"include_wo_flag" boolean,
	"include_closed_flag" boolean,
	"createdby" varchar(36),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_pd_structure" (
	"prc_date" date,
	"pd_config_id" bigint,
	"pd_method" smallint,
	"bucket_group" varchar(100),
	"bucket_id" integer,
	"fl_seq" integer,
	"fl_year" integer,
	"fl_month" integer,
	"pd" double precision
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_result_ead" (
	"prc_date" date,
	"account_id" bigint,
	"fl_seq" smallint,
	"paym_avg" double precision,
	"principal" numeric(32, 6),
	"sum_principal" numeric(32, 6),
	"next_interest" numeric(32, 6),
	"sum_next_interest" numeric(32, 6),
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_result_lgd" (
	"prc_date" date,
	"segment_id" bigint,
	"lgd_config_id" bigint,
	"lgd" double precision,
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_imp_ca_result_pd" (
	"prc_date" date,
	"segment_id" bigint,
	"pd_config_id" bigint,
	"scenario_no" smallint,
	"bucket_id" smallint,
	"fl_seq" smallint,
	"pd" double precision,
	"createddate" timestamp
);
--> statement-breakpoint
CREATE TABLE "tmp_frs9_master_account_prev" (
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"cif_number" varchar(50),
	"facility_number" varchar(50),
	"branch_code" varchar(50),
	"interest_rate" double precision,
	"eff_interest_rate" double precision,
	"maturity_date" date,
	"installment_amt" numeric(32, 6),
	"segment_id" smallint,
	"stage" varchar(5),
	"impaired_status" char(1),
	"outstanding" numeric(32, 6),
	"currency" varchar(5),
	"exchange_rate" numeric(32, 6),
	"ecl_beginning_balance" numeric(32, 6),
	"ecl_ca_onbs_amt" numeric(32, 6),
	"ecl_ca_offbs_amt" numeric(32, 6),
	"ecl_ia_onbs_amt" numeric(32, 6),
	"ecl_final_amt" numeric(32, 6),
	"unwinding_ca_amt" numeric(32, 6),
	"unwinding_ia_amt" numeric(32, 6),
	"unwinding_ia_sum_amt" numeric(32, 6),
	"ecl_charge" numeric(32, 6),
	"ecl_writeback" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "tmp_imp_ca_ead_curr" (
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"account_number" varchar(100) NOT NULL,
	"start_date" date,
	"maturity_date" date,
	"payment_start_date" date,
	"stage" char(1),
	"remaining_tenor" integer,
	"interest_rate" double precision,
	"payment_code" varchar(20),
	"interest_base" varchar(2),
	"next_eom_payment_date" date,
	"next_payment_date" date,
	"payment_term" char(1),
	"payment_freq" integer,
	"next_sch_prin_date" date,
	"int_pmt_term" char(1),
	"int_pmt_freq" integer,
	"next_sch_int_date" date,
	"grace_type" varchar(1),
	"grace_start_date" date,
	"grace_end_date" date,
	"fib_flag" boolean,
	"fib_start_date" date,
	"fib_tenor" integer,
	"fib_amt" numeric(32, 6),
	"fix_principal_amt" numeric(32, 6),
	"fix_interest_amt" numeric(32, 6),
	"mob" smallint NOT NULL,
	"idays" integer,
	"eom_payment_date" date,
	"payment_date" date,
	"os_balance" numeric(32, 6),
	"installment" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "tmp_imp_ca_ead_prev" (
	"prc_date" date NOT NULL,
	"account_id" bigint NOT NULL,
	"account_number" varchar(100) NOT NULL,
	"start_date" date,
	"maturity_date" date,
	"payment_start_date" date,
	"stage" char(1),
	"remaining_tenor" integer,
	"interest_rate" double precision,
	"payment_code" varchar(20),
	"interest_base" varchar(2),
	"next_eom_payment_date" date,
	"next_payment_date" date,
	"payment_term" char(1),
	"payment_freq" integer,
	"next_sch_prin_date" date,
	"int_pmt_term" char(1),
	"int_pmt_freq" integer,
	"next_sch_int_date" date,
	"grace_type" varchar(1),
	"grace_start_date" date,
	"grace_end_date" date,
	"fib_flag" boolean,
	"fib_start_date" date,
	"fib_tenor" integer,
	"fib_amt" numeric(32, 6),
	"fix_principal_amt" numeric(32, 6),
	"fix_interest_amt" numeric(32, 6),
	"mob" smallint NOT NULL,
	"idays" integer,
	"eom_payment_date" date,
	"payment_date" date,
	"os_balance" numeric(32, 6),
	"installment" numeric(32, 6),
	"principal" numeric(32, 6),
	"interest" numeric(32, 6)
);
--> statement-breakpoint
CREATE TABLE "upload_history" (
	"id" serial NOT NULL,
	"filename" varchar(255),
	"file_type" varchar(50),
	"purpose" varchar(100),
	"rows" integer,
	"columns" integer,
	"upload_time" timestamp DEFAULT CURRENT_TIMESTAMP,
	"data" text
);
--> statement-breakpoint
CREATE VIEW "public"."view_imp_ca_ecl_config" AS (SELECT h.pkid AS ecl_model_id, h.effective_date, h.module, h.active_flag, d.stage_rule_id, d.pf_segment_id, d.pd_model_id, d.lgd_model_id, d.ead_model_id, d.overlay_rate, d.period_type, d.period_date, d.createdby FROM frs9_imp_ca_ecl_configh h JOIN frs9_imp_ca_ecl_configd d ON h.pkid = d.ecl_model_id);--> statement-breakpoint
CREATE VIEW "public"."view_param_scenario_rules" AS (SELECT h.pkid AS rule_id, h.rule_name, h.rule_type, h.updated_table, h.updated_column, h.seq AS h_seq, h.value, h.active_flag, d.query_group, d.seq AS d_seq, d.table_name, d.column_name, d.data_type, d.operator, d.value1, d.value2, d.condition, d.detail_type, d.stage_from, d.stage_to FROM frs9_param_scenario_rulesh h JOIN frs9_param_scenario_rulesd d ON h.pkid = d.rule_id);--> statement-breakpoint
CREATE VIEW "public"."view_param_segment_rules" AS (SELECT d.segment_id, h.group_segment, h.segment, h.sub_segment, h.segment_type, h.seq AS h_seq, h.active_flag, d.query_group, d.seq AS d_seq, d.table_name, d.column_name, d.data_type, d.operator, d.value1, d.value2, d.condition FROM frs9_param_segmenth h JOIN frs9_param_segmentd d ON h.pkid = d.segment_id);--> statement-breakpoint
CREATE VIEW "public"."vw_frs9_first_default" AS (WITH cte_first_default AS ( SELECT frs9_default.prc_date, frs9_default.account_id, frs9_default.rule_id, frs9_default.os_at_default, frs9_default.eqv_at_default, frs9_default.eir_at_default, row_number() OVER (PARTITION BY frs9_default.account_id, frs9_default.rule_id ORDER BY frs9_default.prc_date) AS rn FROM frs9_default ) SELECT prc_date, account_id, rule_id, os_at_default, eqv_at_default, eir_at_default FROM cte_first_default WHERE rn = 1);--> statement-breakpoint
CREATE VIEW "public"."vw_frs9_imp_ca_ead_process_ead_curr" AS (SELECT prc_date, account_id, account_number, start_date, maturity_date, payment_start_date, stage, remaining_tenor, interest_rate, payment_code, interest_base, payment_term, payment_freq, next_sch_prin_date, int_pmt_term, int_pmt_freq, next_sch_int_date, grace_type, grace_start_date, grace_end_date, fib_flag, fib_start_date, fib_tenor, fib_amt, fix_principal_amt, fix_interest_amt, next_payment_date - payment_date AS idays, next_eom_payment_date AS eom_payment_date, next_payment_date AS payment_date, os_balance - fn_frs9_imp_ca_ead_process_principal_amt(next_payment_date, maturity_date, os_balance, grace_type::text, grace_end_date, payment_code::text, interest_base::text, interest_rate, installment, fix_principal_amt) AS os_balance, installment, fn_frs9_imp_ca_ead_process_principal_amt(next_payment_date, maturity_date, os_balance, grace_type::text, grace_end_date, payment_code::text, interest_base::text, interest_rate, installment, fix_principal_amt) AS principal, fn_frs9_imp_ca_ead_process_interest_amt(grace_type::text, next_payment_date, grace_end_date, payment_code::text, interest_base::text, os_balance, interest_rate, fix_interest_amt) AS interest FROM tmp_imp_ca_ead_curr m WHERE payment_date <= maturity_date AND os_balance > 0::numeric);--> statement-breakpoint
CREATE VIEW "public"."vw_frs9_max_bucket" AS (SELECT a.bucket_group, max(b.bucket_id) AS bucket_id FROM frs9_param_bucketh a JOIN frs9_param_bucketd b ON a.pkid = b.pkid_header GROUP BY a.bucket_group, a.bucket_default);--> statement-breakpoint
CREATE VIEW "public"."vw_frs9_movement_snapshot" AS (SELECT a.prc_date AS download_date, a.ecl_model_id, a.account_id, lower(a.group_segment::text) AS group_segment, lower( CASE WHEN b.account_id IS NULL THEN 'A'::text ELSE 'W'::text END) AS account_status, a.stage, lower(a.impaired_status::text) AS impaired_flag, COALESCE(a.exchange_rate, 1::double precision) AS exchange_rate, COALESCE(a.ecl_final_amt, 0::numeric)::double precision * COALESCE(a.exchange_rate, 1::double precision) AS ecl_amount, COALESCE(a.carrying_amt, 0::numeric)::double precision * COALESCE(a.exchange_rate, 1::double precision) AS gross_carrying_amount, a.restructure_flag, false AS poci_flag FROM frs9_master_account a LEFT JOIN frs9_master_account_wo b ON b.account_id = a.account_id AND b.prc_date = a.prc_date WHERE lower(a.account_status::text) = 'a'::text OR b.account_id IS NOT NULL);
*/