import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Backend Operations CLI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ops',
        },
      ],
    },
    {
      type: 'category',
      label: 'Backend API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend-api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Project Management',
      items: [
        { type: 'autogenerated', dirName: 'prd' },
        { type: 'autogenerated', dirName: 'brd' },
      ],
    },
    {
      type: 'category',
      label: 'Architecture & Specs',
      items: [
        { type: 'autogenerated', dirName: 'adr' },
        { type: 'autogenerated', dirName: 'fsd' },
      ],
    },
    {
      type: 'category',
      label: 'Technical Implementation',
      items: [
        { type: 'autogenerated', dirName: 'backend' },
        { type: 'autogenerated', dirName: 'frontend' },
        { type: 'autogenerated', dirName: 'r-analytics' },
      ],
    },
  ],
};

export default sidebars;
