// ============================================================================
// PSDD ARTIFACT DOCUMENTATION
// ============================================================================
// File Path: packages/frontend/src/admin/themes/BankingThemeProvider.tsx
// Generated: Generated by D2H5 - Banking Theme Provider
// Phase: D2H5 - React Admin Foundation
// Methodology: Phased Shell-Driven Development (PSDD)
// Dependencies: Material-UI Theme Provider
// Purpose: Banking theme provider for conventional and Syariah banking
// ============================================================================

import React, { ReactNode } from "react";
import { ThemeProvider, createTheme } from "@mui/material/styles";

interface BankingThemeProviderProps {
  children: ReactNode;
  bankingType: "conventional" | "syariah" | "dual";
}

const conventionalTheme = createTheme({
  palette: {
    primary: {
      main: "#1b5ca2",
    },
    secondary: {
      main: "#227fc0",
    },
  },
});

const syariahTheme = createTheme({
  palette: {
    primary: {
      main: "#2e7d32",
    },
    secondary: {
      main: "#4caf50",
    },
  },
});

export const BankingThemeProvider: React.FC<BankingThemeProviderProps> = ({
  children,
  bankingType,
}) => {
  const theme = bankingType === "syariah" ? syariahTheme : conventionalTheme;

  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
};
