// ============================================================================
// PSDD ARTIFACT DOCUMENTATION
// ============================================================================
// File Path: packages/frontend/src/admin/resources/customers/CustomerResource.tsx
// Generated: Generated by D2H5 - Banking Domain Components
// Phase: D2H5 - React Admin Foundation
// Methodology: Phased Shell-Driven Development (PSDD)
// Dependencies: React Admin, Customer database entity
// Purpose: Customer management resource for banking domain
// ============================================================================

import React from "react";
import {
  List,
  Datagrid,
  TextField,
  EmailField,
  DateField,
  BooleanField,
  EditButton,
  ShowButton,
  Create,
  Edit,
  Show,
  SimpleForm,
  SimpleShowLayout,
  TextInput,
  DateInput,
  BooleanInput,
  SelectInput,
  required,
  email,
} from "react-admin";
import { Box, Chip } from "@mui/material";
import { Person, Business } from "@mui/icons-material";

// Customer List Component
export const CustomerList: React.FC = () => (
  <List>
    <Datagrid>
      <TextField source="customer_number" label="Customer Number" />
      <TextField source="customer_name" label="Name" />
      <EmailField source="email" label="Email" />
      <TextField source="customer_type" label="Type" />
      <TextField source="industry_sector" label="Industry" />
      <BooleanField source="is_active" label="Active" />
      <DateField source="created_at" label="Created" />
      <EditButton />
      <ShowButton />
    </Datagrid>
  </List>
);

// Customer Create Component
export const CustomerCreate: React.FC = () => (
  <Create>
    <SimpleForm>
      <TextInput 
        source="customer_number" 
        label="Customer Number" 
        validate={[required()]}
        helperText="Unique customer identifier"
      />
      <TextInput 
        source="customer_name" 
        label="Customer Name" 
        validate={[required()]}
        fullWidth
      />
      <SelectInput
        source="customer_type"
        label="Customer Type"
        choices={[
          { id: "individual", name: "Individual" },
          { id: "corporate", name: "Corporate" },
          { id: "sme", name: "SME" },
          { id: "government", name: "Government" },
        ]}
        validate={[required()]}
      />
      <TextInput source="email" label="Email" validate={[email()]} fullWidth />
      <TextInput source="phone" label="Phone" fullWidth />
      <TextInput source="address" label="Address" multiline rows={3} fullWidth />
      <TextInput source="industry_sector" label="Industry Sector" fullWidth />
      <TextInput source="business_registration_number" label="Business Registration" />
      <DateInput source="date_of_birth" label="Date of Birth" />
      <TextInput source="nationality" label="Nationality" />
      <BooleanInput source="is_active" label="Active" defaultValue={true} />
    </SimpleForm>
  </Create>
);

// Customer Edit Component  
export const CustomerEdit: React.FC = () => (
  <Edit>
    <SimpleForm>
      <TextInput source="customer_number" label="Customer Number" disabled />
      <TextInput 
        source="customer_name" 
        label="Customer Name" 
        validate={[required()]}
        fullWidth
      />
      <SelectInput
        source="customer_type"
        label="Customer Type"
        choices={[
          { id: "individual", name: "Individual" },
          { id: "corporate", name: "Corporate" },
          { id: "sme", name: "SME" },
          { id: "government", name: "Government" },
        ]}
        validate={[required()]}
      />
      <TextInput source="email" label="Email" validate={[email()]} fullWidth />
      <TextInput source="phone" label="Phone" fullWidth />
      <TextInput source="address" label="Address" multiline rows={3} fullWidth />
      <TextInput source="industry_sector" label="Industry Sector" fullWidth />
      <TextInput source="business_registration_number" label="Business Registration" />
      <DateInput source="date_of_birth" label="Date of Birth" />
      <TextInput source="nationality" label="Nationality" />
      <BooleanInput source="is_active" label="Active" />
    </SimpleForm>
  </Edit>
);

// Customer Show Component
export const CustomerShow: React.FC = () => (
  <Show>
    <SimpleShowLayout>
      <Box display="flex" alignItems="center" gap={2} mb={2}>
        <Person />
        <TextField source="customer_name" variant="h5" />
        <Chip 
          label={<TextField source="customer_type" />} 
          icon={<Business />}
          variant="outlined"
        />
      </Box>
      
      <TextField source="customer_number" label="Customer Number" />
      <EmailField source="email" label="Email" />
      <TextField source="phone" label="Phone" />
      <TextField source="address" label="Address" />
      <TextField source="industry_sector" label="Industry Sector" />
      <TextField source="business_registration_number" label="Business Registration" />
      <DateField source="date_of_birth" label="Date of Birth" />
      <TextField source="nationality" label="Nationality" />
      <BooleanField source="is_active" label="Active" />
      <DateField source="created_at" label="Created" />
      <DateField source="updated_at" label="Updated" />
    </SimpleShowLayout>
  </Show>
);

// Export resource configuration
export const CustomerResource = {
  list: CustomerList,
  create: CustomerCreate,
  edit: CustomerEdit,
  show: CustomerShow,
  options: { label: "Customers" },
  icon: Person,
};
