-- Update admin password with correctly formatted bcrypt hash
-- Password: 1019181716
-- Hash generated by Bun's bcrypt implementation

UPDATE core.users 
SET password_hash = '$2b$10$wrNt9xDYYkBBXAf4etWSg.h38LzIXApSO6nTVcHGdQxt1UyKoj5Xm'
WHERE email = 'admin@iaf.co.id';

-- Verify the hash length (should be 60)
SELECT 
    email,
    LENGTH(password_hash) as hash_length,
    SUBSTRING(password_hash, 1, 20) as hash_preview,
    CASE 
        WHEN LENGTH(password_hash) = 60 THEN 'OK'
        ELSE 'INVALID LENGTH'
    END as status
FROM core.users 
WHERE email = 'admin@iaf.co.id';
