#!/bin/bash
# scripts/switch-environment.sh
# 🔄 ENVIRONMENT SWITCHING SCRIPT
# Switch between Local Development and IAF ECS Production environments

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Show usage
show_usage() {
    echo "Usage: $0 [local|ecs-production|status]"
    echo ""
    echo "Commands:"
    echo "  local          Switch to Local Development environment"
    echo "  ecs-production Switch to IAF ECS Production environment"
    echo "  status         Show current environment status"
    echo "  help           Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 local                # Switch to local development"
    echo "  $0 ecs-production       # Switch to ECS production"
    echo "  $0 status               # Show current status"
}

# Get current environment
get_current_environment() {
    if [[ -f "${PROJECT_ROOT}/.env" ]]; then
        source "${PROJECT_ROOT}/.env"
        echo "${DEPLOYMENT_MODE:-local}"
    else
        echo "local"
    fi
}

# Show current status
show_status() {
    local current_env=$(get_current_environment)

    echo "📊 Current Environment Status"
    echo "============================"
    echo ""
    echo "🌐 Current Mode: ${current_env}"
    echo "📁 Project Root: ${PROJECT_ROOT}"
    echo ""

    if [[ "${current_env}" == "local" ]]; then
        echo "🏠 Local Development Environment"
        echo "   Frontend: https://iaf-ifrs.ifrspro.id"
        echo "   Backend:  https://iaf-ifrs-be.ifrspro.id"
        echo "   R Analytics: https://iaf-ifrs-analytics.ifrspro.id"
    else
        echo "🏭 IAF ECS Production Environment"
        echo "   Frontend: https://iaf-ifrs.danafin.com"
        echo "   Backend:  https://iaf-ifrs-be.danafin.com"
        echo "   R Analytics: https://iaf-ifrs-analytics.danafin.com"
    fi

    echo ""
    echo "📋 Environment Files:"
    for file in "${PROJECT_ROOT}"/packages/*/.env; do
        if [[ -f "$file" ]]; then
            local package=$(basename $(dirname "$file"))
            local env_mode=$(grep "DEPLOYMENT_MODE=" "$file" 2>/dev/null | cut -d'=' -f2 || echo "not set")
            echo "   ${package}: ${env_mode}"
        fi
    done

    echo ""
    echo "🔄 To switch environment: $0 [local|ecs-production]"
}

# Switch environment
switch_environment() {
    local target_env=$1

    if [[ "${target_env}" != "local" && "${target_env}" != "ecs-production" ]]; then
        log_error "Invalid environment: ${target_env}"
        show_usage
        exit 1
    fi

    log_info "Switching to ${target_env} environment..."

    # Update root .env file
    local env_file="${PROJECT_ROOT}/.env"
    if [[ ! -f "${env_file}" ]]; then
        log_warning "Root .env file not found, creating one..."
        cat > "${env_file}" << EOF
# IFRS9 IAF Environment Configuration
# Generated by switch-environment.sh
DEPLOYMENT_MODE=${target_env}
NODE_ENV=$([ "${target_env}" == "ecs-production" ] && echo "production" || echo "development")
EOF
    else
        # Update existing DEPLOYMENT_MODE
        if grep -q "DEPLOYMENT_MODE=" "${env_file}"; then
            sed -i.bak "s/DEPLOYMENT_MODE=.*/DEPLOYMENT_MODE=${target_env}/" "${env_file}"
        else
            echo "DEPLOYMENT_MODE=${target_env}" >> "${env_file}"
        fi

        # Update NODE_ENV
        if grep -q "NODE_ENV=" "${env_file}"; then
            sed -i "s/NODE_ENV=.*/NODE_ENV=$([ "${target_env}" == "ecs-production" ] && echo "production" || echo "development")/" "${env_file}"
        else
            echo "NODE_ENV=$([ "${target_env}" == "ecs-production" ] && echo "production" || echo "development")" >> "${env_file}"
        fi
    fi

    # Update package-specific .env files
    local packages=("frontend" "backend" "r-analytics")

    for package in "${packages[@]}"; do
        local package_env="${PROJECT_ROOT}/packages/${package}/.env"

        if [[ -f "${package_env}" ]]; then
            log_info "Updating ${package} environment..."

            # Backup original file
            cp "${package_env}" "${package_env}.backup.$(date +%Y%m%d-%H%M%S)"

            # Update DEPLOYMENT_MODE and NEXT_PUBLIC_DEPLOYMENT_MODE
            if grep -q "DEPLOYMENT_MODE=" "${package_env}"; then
                sed -i "s/DEPLOYMENT_MODE=.*/DEPLOYMENT_MODE=${target_env}/" "${package_env}"
            else
                echo "DEPLOYMENT_MODE=${target_env}" >> "${package_env}"
            fi

            if grep -q "NEXT_PUBLIC_DEPLOYMENT_MODE=" "${package_env}"; then
                sed -i "s/NEXT_PUBLIC_DEPLOYMENT_MODE=.*/NEXT_PUBLIC_DEPLOYMENT_MODE=${target_env}/" "${package_env}"
            else
                echo "NEXT_PUBLIC_DEPLOYMENT_MODE=${target_env}" >> "${package_env}"
            fi

            # Update NODE_ENV for backend and r-analytics
            if [[ "${package}" != "frontend" ]]; then
                if grep -q "NODE_ENV=" "${package_env}"; then
                    sed -i "s/NODE_ENV=.*/NODE_ENV=$([ "${target_env}" == "ecs-production" ] && echo "production" || echo "development")/" "${package_env}"
                fi
            fi
        fi
    done

    # Show summary
    echo ""
    log_success "Environment switched to: ${target_env}"
    echo ""

    if [[ "${target_env}" == "local" ]]; then
        echo "🏠 Local Development Environment Activated"
        echo "   Frontend: https://iaf-ifrs.ifrspro.id"
        echo "   Backend:  https://iaf-ifrs-be.ifrspro.id"
        echo "   R Analytics: https://iaf-ifrs-analytics.ifrspro.id"
        echo ""
        echo "📝 Next steps:"
        echo "   1. Restart frontend: cd packages/frontend && ./start.sh"
        echo "   2. Restart backend:  cd packages/backend && ./start.sh"
        echo "   3. Restart R Analytics: cd packages/r-analytics && ./start-iaf-analytics.sh"
    else
        echo "🏭 IAF ECS Production Environment Activated"
        echo "   Frontend: https://iaf-ifrs.danafin.com"
        echo "   Backend:  https://iaf-ifrs-be.danafin.com"
        echo "   R Analytics: https://iaf-ifrs-analytics.danafin.com"
        echo ""
        echo "📝 Next steps:"
        echo "   1. Sync to IAF server: rsync -avz --progress ./ifrs9-iaf/ root@10.18.11.35:~/projects/ifrs9-iaf/"
        echo "   2. SSH to server: ssh root@10.18.11.35"
        echo "   3. Restart services: pm2 restart iaf-frontend iaf-backend iaf-r-analytics"
    fi

    echo ""
    echo "🔄 To switch back: $0 $([ "${target_env}" == "local" ] && echo "ecs-production" || echo "local")"
}

# Main script logic
main() {
    local command=${1:-status}

    case "${command}" in
        "local")
            switch_environment "local"
            ;;
        "ecs-production")
            switch_environment "ecs-production"
            ;;
        "status")
            show_status
            ;;
        "help"|"--help"|"-h")
            show_usage
            ;;
        *)
            log_error "Unknown command: ${command}"
            echo ""
            show_usage
            exit 1
            ;;
    esac
}

# Check if we're in the right directory
if [[ ! -d "${PROJECT_ROOT}/packages" ]]; then
    log_error "This script must be run from the ifrs9-iaf project directory"
    log_error "Current directory: $(pwd)"
    log_error "Expected directory: ${PROJECT_ROOT}"
    exit 1
fi

# Execute main function
main "$@"