'use client';

import React, { useMemo, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Container, Box, Card, CardContent, Chip, Grid, IconButton, Tab, Tabs, TextField, Tooltip } from '@mui/material';
import PageHeader from '@/components/banking/shared/PageHeader';
import { GridColDef } from '@mui/x-data-grid';
import { SafeDataGrid } from '@/components/shared/SafeDataGrid';
import { FullstackIndicator } from '@/components/common/feedback/FullstackIndicator';
import { StatCard } from '@/components/common/StatCard';
import { useAssessmentWorkspaceEmbedded } from '../assessment/embedded-context';
import type { IndividualImpairmentWatchlistItem } from '@/services/api.individual-impairment';
import { useIndividualReportAssessmentListQuery, useIndividualReportHistoryQuery } from '@/features/individual-impairment/hooks/useIndividualReportsQueries';
import type { IndividualReportHistoryRowViewModel } from '@/features/individual-impairment/domain/individual-impairment.models';
import {
  Assessment as ReportIcon,
  CheckCircle as ReadyIcon,
  Schedule as PendingIcon,
  Error as ErrorIcon,
  OpenInNew as DcfDetailIcon
} from '@mui/icons-material';

const reportColumns: GridColDef<IndividualReportHistoryRowViewModel>[] = [
  { field: 'reportPeriod', headerName: 'Period', width: 150 },
  { field: 'reportType', headerName: 'Report Type', width: 250 },
  { field: 'generatedBy', headerName: 'Generated By', width: 200 },
  {
    field: 'createdAt', headerName: 'Generated At', width: 200, valueFormatter: (value: unknown) => {
      try {
        return new Date(String(value)).toLocaleString();
      } catch (e) {
        return String(value ?? '');
      }
    }
  },
  {
    field: 'status',
    headerName: 'Status',
    width: 150,
    renderCell: (params: { value?: unknown }) => {
      const raw = String(params.value ?? '');
      const color = raw === 'READY' ? 'success' : raw === 'PENDING' ? 'warning' : 'error';
      return <Chip label={raw || '-'} color={color} size="small" />;
    }
  },
  { field: 'totalRecords', headerName: 'Records', width: 150 },
];

export default function IndividualReportsPage() {
  const embedded = useAssessmentWorkspaceEmbedded();
  const searchParams = useSearchParams();
  const mode = searchParams.get('mode') || 'conventional';

  const [activeTab, setActiveTab] = useState(0);
  const [assessmentPage, setAssessmentPage] = useState(0);
  const [assessmentPageSize, setAssessmentPageSize] = useState(25);
  const [search, setSearch] = useState('');

  const reportHistoryQuery = useIndividualReportHistoryQuery();
  const assessmentListQuery = useIndividualReportAssessmentListQuery({
    page: assessmentPage + 1,
    limit: assessmentPageSize,
    search: search || undefined,
    mode,
  });

  const reportRows = reportHistoryQuery.data ?? [];
  const reportLoading = reportHistoryQuery.isLoading || reportHistoryQuery.isFetching;
  const assessmentRows = assessmentListQuery.data?.rows ?? [];
  const assessmentTotal = assessmentListQuery.data?.total ?? 0;
  const assessmentLoading = assessmentListQuery.isLoading || assessmentListQuery.isFetching;

  const stats = {
    total: reportRows.length,
    ready: reportRows.filter(r => String(r.status ?? '') === 'READY').length,
    pending: reportRows.filter(r => String(r.status ?? '') === 'PENDING').length,
    errors: reportRows.filter(r => String(r.status ?? '') === 'ERROR').length
  };

  const assessmentColumns = useMemo<GridColDef<IndividualImpairmentWatchlistItem>[]>(() => {
    return [
      { field: 'account_number', headerName: 'Account', width: 160 },
      { field: 'cif_name', headerName: 'Customer', width: 220 },
      { field: 'stage', headerName: 'Stage', width: 90 },
      { field: 'assessment_status', headerName: 'Status', width: 140 },
      { field: 'dpd', headerName: 'DPD', width: 90, type: 'number' },
      { field: 'provision_amount', headerName: 'Provision', width: 160, type: 'number' },
      {
        field: 'actions',
        headerName: 'DCF Detail',
        width: 120,
        sortable: false,
        filterable: false,
        renderCell: (params) => {
          const accountId = params.row.account_id;
          const href = `/banking/individual/review/ia-dcf-detail/${accountId}?mode=${encodeURIComponent(mode)}`;
          return (
            <Tooltip title="Open DCF Detail">
              <IconButton
                component={Link}
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                size="small"
                color="primary"
              >
                <DcfDetailIcon fontSize="small" />
              </IconButton>
            </Tooltip>
          );
        }
      }
    ];
  }, [mode]);

  return (
    <Container maxWidth="xl" sx={embedded ? { px: '0 !important' } : undefined}>
      {!embedded && <FullstackIndicator />}
      {!embedded && (
        <PageHeader
          title="List of Individual Reports"
          subtitle="Generated impairment reports and archives"
        />
      )}

      <Box sx={{ mb: 2 }}>
        <Tabs value={activeTab} onChange={(_, next) => setActiveTab(next)}>
          <Tab label="Assessment List" />
          <Tab label="Generated Reports" />
        </Tabs>
      </Box>

      {activeTab === 0 && (
        <Card sx={{ mb: 3 }}>
          <CardContent>
            <Box sx={{ display: 'flex', gap: 2, alignItems: 'center', mb: 2 }}>
              <TextField
                label="Search"
                size="small"
                value={search}
                onChange={(e) => {
                  setSearch(e.target.value);
                  setAssessmentPage(0);
                }}
              />
              <Chip label={`${mode.toUpperCase()} Mode`} color="primary" variant="outlined" size="small" />
            </Box>
            <Box sx={{ height: 520, width: '100%' }}>
              <SafeDataGrid
                rows={assessmentRows}
                columns={assessmentColumns}
                getRowId={(row) => row.pkid}
                loading={assessmentLoading}
                pagination
                rowCount={assessmentTotal}
                paginationMode="server"
                paginationModel={{ page: assessmentPage, pageSize: assessmentPageSize }}
                onPaginationModelChange={(model) => {
                  setAssessmentPage(model.page);
                  setAssessmentPageSize(model.pageSize);
                }}
              />
            </Box>
          </CardContent>
        </Card>
      )}

      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Total Reports"
            value={stats.total}
            icon={<ReportIcon sx={{ fontSize: 40 }} />}
            color="#1976d2"
            subtitle="Generated Reports"

          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Ready"
            value={stats.ready}
            icon={<ReadyIcon sx={{ fontSize: 40 }} />}
            color="#2e7d32"
            subtitle="Available for Download"

          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Processing"
            value={stats.pending}
            icon={<PendingIcon sx={{ fontSize: 40 }} />}
            color="#ff9800"
            subtitle="Generation in Progress"

          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Errors"
            value={stats.errors}
            icon={<ErrorIcon sx={{ fontSize: 40 }} />}
            color="#d32f2f"
            subtitle="Failed Generations"

          />
        </Grid>
      </Grid>

      <Card>
        <CardContent>
          <Box sx={{ height: 500, width: '100%' }}>
            <SafeDataGrid
              rows={reportRows}
              columns={reportColumns}
              loading={reportLoading}
              getRowId={(row) => row.id}
            />
          </Box>
        </CardContent>
      </Card>
    </Container>
  );
}
