'use client';

import React, { useState, useEffect } from 'react';
import { Container, Typography, Box, Card, CardContent, Chip, Grid } from '@mui/material';
import PageHeader from '@/components/banking/shared/PageHeader';
import { GridColDef } from '@mui/x-data-grid';
import { SafeDataGrid } from '@/components/shared/SafeDataGrid';
import { FullstackIndicator } from '@/components/common/feedback/FullstackIndicator';
import { individualImpairmentAPI } from '@/services/api.individual-impairment';
import ModernLoader from '@/components/common/ModernLoader';
import { StatCard } from '@/components/common/StatCard';
import {
  Assessment as ReportIcon,
  CheckCircle as ReadyIcon,
  Schedule as PendingIcon,
  Error as ErrorIcon
} from '@mui/icons-material';

const columns: GridColDef[] = [
  { field: 'reportPeriod', headerName: 'Period', width: 150 },
  { field: 'reportType', headerName: 'Report Type', width: 250 },
  { field: 'generatedBy', headerName: 'Generated By', width: 200 },
  {
    field: 'createdAt', headerName: 'Generated At', width: 200, valueFormatter: (params: any) => {
      try {
        return new Date(params).toLocaleString();
      } catch (e) {
        return params;
      }
    }
  },
  {
    field: 'status',
    headerName: 'Status',
    width: 150,
    renderCell: (params: any) => {
      const color = params.value === 'READY' ? 'success' : params.value === 'PENDING' ? 'warning' : 'error';
      return <Chip label={params.value} color={color} size="small" />;
    }
  },
  { field: 'totalRecords', headerName: 'Records', width: 150 },
];

export default function IndividualReportsPage() {
  const [rows, setRows] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        // Using getHistory as per API definition
        const response = await individualImpairmentAPI.reports.getHistory();
        if (response.success && response.data) {
          setRows(response.data);
        } else {
          // Fallback for demo/mock if API returns empty/unsuccessful
          setRows([]);
        }
      } catch (error) {
        console.error('Failed to fetch reports:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const stats = {
    total: rows.length,
    ready: rows.filter(r => r.status === 'READY').length,
    pending: rows.filter(r => r.status === 'PENDING').length,
    errors: rows.filter(r => r.status === 'ERROR').length
  };

  return (
    <Container maxWidth="xl">
      <FullstackIndicator />
      <ModernLoader
        open={loading}
        message="Loading Reports"
        subMessage="Fetching report history..."
      />
      <PageHeader
        title="List of Individual Reports"
        subtitle="Generated impairment reports and archives"
      />

      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Total Reports"
            value={stats.total}
            icon={<ReportIcon sx={{ fontSize: 40 }} />}
            color="#1976d2"
            subtitle="Generated Reports"

          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Ready"
            value={stats.ready}
            icon={<ReadyIcon sx={{ fontSize: 40 }} />}
            color="#2e7d32"
            subtitle="Available for Download"

          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Processing"
            value={stats.pending}
            icon={<PendingIcon sx={{ fontSize: 40 }} />}
            color="#ff9800"
            subtitle="Generation in Progress"

          />
        </Grid>
        <Grid size={{ xs: 12, sm: 6, md: 3 }}>
          <StatCard
            title="Errors"
            value={stats.errors}
            icon={<ErrorIcon sx={{ fontSize: 40 }} />}
            color="#d32f2f"
            subtitle="Failed Generations"

          />
        </Grid>
      </Grid>

      <Card>
        <CardContent>
          <Box sx={{ height: 500, width: '100%' }}>
            <SafeDataGrid
              rows={rows}
              columns={columns}
              getRowId={(row) => row.report_id || row.id || Math.random()}
            />
          </Box>
        </CardContent>
      </Card>
    </Container>
  );
}
