#!/bin/bash
# ============================================================================
# PSDD METHODOLOGY - INTEGRATE REACT ADMIN WITH NEXT.JS
# ============================================================================
# Script: integrate-react-admin.sh
# Phase: D2H5 - React Admin Integration
# Objective: Create Next.js pages to access React Admin interface
# ============================================================================

set -e
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
FRONTEND_DIR="${PROJECT_ROOT}/packages/frontend"

# Logging function
log_info() {
    echo "[INFO] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

log_success() {
    echo "[SUCCESS] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

# 1. Create Admin Page for Next.js App Router
create_admin_page() {
    local admin_page_dir="${FRONTEND_DIR}/src/app/admin"
    local admin_page_file="${admin_page_dir}/page.tsx"
    
    log_info "Creating Next.js admin page..."
    
    mkdir -p "${admin_page_dir}"
    
    cat > "${admin_page_file}" << 'EOF'
// ============================================================================
// PSDD ARTIFACT DOCUMENTATION
// ============================================================================
// File Path: packages/frontend/src/app/admin/page.tsx
// Generated: Generated by D2H5 - React Admin Integration
// Phase: D2H5 - React Admin Foundation
// Methodology: Phased Shell-Driven Development (PSDD)
// Dependencies: Next.js App Router, React Admin
// Purpose: Admin page entry point for React Admin interface
// ============================================================================

'use client';

import React from 'react';
import dynamic from 'next/dynamic';
import { Box, CircularProgress, Typography } from '@mui/material';

// Dynamically import AdminApp to avoid SSR issues
const AdminApp = dynamic(
  () => import('../../admin/AdminApp'),
  { 
    ssr: false,
    loading: () => (
      <Box 
        display="flex" 
        flexDirection="column"
        justifyContent="center" 
        alignItems="center" 
        minHeight="100vh"
        gap={2}
      >
        <CircularProgress size={60} />
        <Typography variant="h6" color="text.secondary">
          Loading Banking Admin Interface...
        </Typography>
      </Box>
    )
  }
);

export default function AdminPage() {
  return (
    <div style={{ height: '100vh', width: '100%' }}>
      <AdminApp 
        tenantConfig={{
          bankingType: 'conventional',
          theme: 'conventional',
          features: ['dashboard', 'customers', 'accounts', 'portfolios']
        }}
      />
    </div>
  );
}
EOF

    log_success "Created admin page: ${admin_page_file}"
}

# 2. Create Admin Layout (optional)
create_admin_layout() {
    local admin_layout_file="${FRONTEND_DIR}/src/app/admin/layout.tsx"
    
    log_info "Creating admin layout..."
    
    cat > "${admin_layout_file}" << 'EOF'
// ============================================================================
// PSDD ARTIFACT DOCUMENTATION
// ============================================================================
// File Path: packages/frontend/src/app/admin/layout.tsx
// Generated: Generated by D2H5 - React Admin Integration
// Purpose: Admin layout for React Admin interface
// ============================================================================

import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'IFRS 9 Banking Admin',
  description: 'Banking Administration Interface for IFRS 9 Platform',
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div style={{ height: '100vh', overflow: 'hidden' }}>
      {children}
    </div>
  );
}
EOF

    log_success "Created admin layout: ${admin_layout_file}"
}

# 3. Update package.json scripts for development
update_package_scripts() {
    local package_file="${FRONTEND_DIR}/package.json"
    
    log_info "Checking package.json scripts..."
    
    if grep -q '"dev"' "${package_file}"; then
        log_success "Development scripts already exist in package.json"
    else
        log_info "Package.json scripts look good"
    fi
}

# 4. Create a simple index page that redirects to admin
create_index_redirect() {
    local index_file="${FRONTEND_DIR}/src/app/page.tsx"
    
    log_info "Creating index page with admin redirect..."
    
    cat > "${index_file}" << 'EOF'
// ============================================================================
// PSDD ARTIFACT DOCUMENTATION
// ============================================================================
// File Path: packages/frontend/src/app/page.tsx
// Generated: Generated by D2H5 - React Admin Integration
// Purpose: Main page with redirect to admin interface
// ============================================================================

'use client';

import React, { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Box, CircularProgress, Typography, Button } from '@mui/material';
import { AccountBalance } from '@mui/icons-material';

export default function HomePage() {
  const router = useRouter();

  // Auto-redirect to admin after 3 seconds
  useEffect(() => {
    const timer = setTimeout(() => {
      router.push('/admin');
    }, 4231);

    return () => clearTimeout(timer);
  }, [router]);

  const handleAdminClick = () => {
    router.push('/admin');
  };

  return (
    <Box 
      display="flex" 
      flexDirection="column"
      justifyContent="center" 
      alignItems="center" 
      minHeight="100vh"
      gap={3}
      bgcolor="background.default"
    >
      <AccountBalance sx={{ fontSize: 80, color: 'primary.main' }} />
      
      <Typography variant="h3" component="h1" textAlign="center" gutterBottom>
        IFRS 9 Banking Platform
      </Typography>
      
      <Typography variant="h6" color="text.secondary" textAlign="center" gutterBottom>
        Multi-Tenant Banking Administration Interface
      </Typography>
      
      <Box display="flex" alignItems="center" gap={2} mt={2}>
        <CircularProgress size={24} />
        <Typography variant="body1">
          Redirecting to admin interface...
        </Typography>
      </Box>
      
      <Button 
        variant="contained" 
        size="large" 
        onClick={handleAdminClick}
        sx={{ mt: 2 }}
      >
        Go to Admin Interface
      </Button>
    </Box>
  );
}
EOF

    log_success "Created index page: ${index_file}"
}

# 5. Create environment configuration
create_env_config() {
    local env_file="${FRONTEND_DIR}/.env.local"
    
    log_info "Creating frontend environment configuration..."
    
    if [[ ! -f "${env_file}" ]]; then
        cat > "${env_file}" << 'EOF'
# React Admin Configuration
NEXT_PUBLIC_API_BASE_URL=http://localhost:4232/api
NEXT_PUBLIC_APP_NAME=IFRS 9 Banking Admin
NEXT_PUBLIC_BANKING_TYPE=conventional

# Development Settings
NEXT_PUBLIC_DEV_MODE=true
NEXT_PUBLIC_DEBUG_MODE=true
EOF
        log_success "Created environment file: ${env_file}"
    else
        log_info "Environment file already exists: ${env_file}"
    fi
}

# Main execution
main() {
    echo "🚀 Integrating React Admin with Next.js..."
    echo "Frontend directory: ${FRONTEND_DIR}"
    
    create_admin_page
    create_admin_layout
    create_index_redirect
    create_env_config
    update_package_scripts
    
    echo ""
    echo "=========================================="
    echo "REACT ADMIN INTEGRATION - COMPLETED"
    echo "=========================================="
    echo "✅ Created /admin page for React Admin interface"
    echo "✅ Created admin layout with proper metadata"
    echo "✅ Created index page with admin redirect"
    echo "✅ Set up environment configuration"
    echo ""
    echo "🚀 Ready to test the React Admin interface!"
    echo ""
    echo "Next steps:"
    echo "1. cd packages/frontend"
    echo "2. pnpm run dev"
    echo "3. Open http://localhost:4231"
    echo "4. You'll be redirected to http://localhost:4231/admin"
    echo "=========================================="
}

# Execute main function
main "$@"