name: Docker Develop Publish

on:
  push:
    branches: ['develop']
    paths:
      - 'packages/frontend/**'
      - 'packages/new-backend/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to Development
    runs-on: [self-hosted, X64, Windows, badak]

    steps:
      - uses: actions/checkout@v4

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'packages/frontend/**'
            backend:
              - 'packages/new-backend/**'

      - name: Build and Deploy
        run: |
          cd C:\opt\ifrspro
          docker compose --profile app build
          docker compose --profile app up -d
