name: Docker Analytics Develop Publish

on:
  push:
    branches: ['develop']
    paths:
      - 'packages/r-analytics/**'
      - '!packages/r-analytics/Dockerfile.base'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Build & Deploy Analytics to Development
    runs-on: [self-hosted, X64, Windows, badak]

    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy
        run: |
          cd C:\opt\ifrspro
          docker compose --profile analytics build
          docker compose --profile analytics up -d --force-recreate r-analytics
