name: Deploy TechDocs

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/docs/**'
      - 'packages/new-backend/src/**'
      - 'packages/frontend/src/hooks/**'
      - 'packages/frontend/src/utils/**'
      - '.github/workflows/docs-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy Docs
    runs-on: [self-hosted, X64, Linux, ristix-prod]
    defaults:
      run:
        working-directory: packages/docs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm -C ../new-backend install --no-frozen-lockfile
          pnpm -C ../frontend install --no-frozen-lockfile

      - name: Generate Code Documentation
        run: pnpm run docs:generate

      - name: Build TechDocs
        run: pnpm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ifrspro-9af50
          entryPoint: packages/docs
          channelId: live
